### ISSUE TITLE
It's not working on the IE9

### ISSUE THREAD

**Issue by phanthinh** [jasonday/printThis#101]
Hi 

I saw error message below when running my website on the IE9:
```

SCRIPT5 Access is denied

printThis.js, line 1001, character 13
```

**Comment by oculus42** [comment]
Are there script tags in the area you are trying to print with .printThis()?

**Comment by oculus42** [comment]
@phanthinh Any follow-up?

**Comment by oculus42** [comment]
@phanthinh 1.10.0 adds a `removeScripts` option. Enable that option, and let us know if you still have this issue.

**Comment by oculus42** [comment]
@phanthinh Any followup? It's been almost two months since your message, and nearly three weeks since the last suggestion from us.

**Comment by oculus42** [comment]
Closing due to no response.
