### ISSUE TITLE
font on the printer

### ISSUE THREAD

**Issue by natanh** [jasonday/printThis#102]
> in the option i added the loadCSS: "my.css" but it keep printing other fonts and fonts size then the page.

====================================================================

###### `[  paste a link to an example (demo or active link) of the issue here ]`  

Your issue may be closed without active code to debug. Options include jsfiddle, jsbin, codepen, dropbox, etc. with code highlighting the specific issue you are having

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is the observed behaviour?

...  

====================================================================

#### When you set `debug:true` and inspect the iframe, what do you see?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which printThis version are you using?
- Did this work before?

**Comment by jasonday** [comment]
Please note: I will need more information to be able to assist you with your issue. Notice the additional details sections outlined in the ticket.

**Comment by oculus42** [comment]
@natanh Please provide some additional detail.

If you look in the network tab of your browser's developer tools, do you see `my.css` load successfully? You might need to provide the path to the file – `/styles/my.css` or whatever is appropriate for your site – and not just the file name.

Beyond that guess, we need more information to offer meaningful support.

**Comment by oculus42** [comment]
@natanh Over three weeks since your issue was opened. Any additional details for follow-up?

**Comment by oculus42** [comment]
Closing due to no response.
