### ISSUE TITLE
No hyphenation with "hyphens: auto"

### ISSUE THREAD

**Issue by theBear** [jasonday/printThis#109]
Hi, thanks for doing this great plugin! I really appreciate this and it's really helpful. Well done!

Unfortunately it's not possible to print the css-property "hyphens" correctly.

- **hyphens: auto** > no hyphenation
- **hyphens: manual** > hyphenation, only if tagged with `&shy;` like hy`&shy;`phe`&shy;`na`&shy;`tion

Is it a bug, can you reproduce the issue? 

I really need this hyphens-property to print out tables with small columns and many/long words.

**Comment by jasonday** [comment]
@theBear can you please provide:

- an example, demo, etc?
- what you see when you inspect the printing iframe (set `debug:true` )?

**Comment by oculus42** [comment]
@theBear Does the hyphenation work with normal print? It looks like [CSS Hyphens are quite poorly supported as yet](http://caniuse.com/#feat=css-hyphens). You might also try `word-break: all` – it's not as pretty, but it should be effective.

**Comment by oculus42** [comment]
@theBear Any follow-up? It's been over two weeks since we heard from you.

**Comment by jasonday** [comment]
No response. Closing.
