### ISSUE TITLE
Print Without margins our Titles/dates etc

### ISSUE THREAD

**Issue by bigdavelamb** [jasonday/printThis#11]
Hello, 

I am using the script to print a barcode, however I would like to print it right in the top left corner and without titles or page numbers. As the user is going to print it on a little sticker printer(Dymo printer) that only has room for the barcode. Here is a screenshot of what I get when printed via IE. Thank you for any help.

![about_blank](https://f.cloud.github.com/assets/4396461/488020/6c26f5ea-b971-11e2-8213-841a080001f0.jpg)

Dave

**Comment by toxicsec22** [comment]
![capture](https://user-images.githubusercontent.com/23154285/34367331-6c62d976-eae4-11e7-9c15-87cfbdffb149.PNG)

Hi sir jason how can i remove the url title in paper ?. Thank you so much
