### ISSUE TITLE
Fit Content To Page Size A4, A3 or Break in to Several Pages According To The Length Of Content

### ISSUE THREAD

**Issue by TharakaMadhusanka** [jasonday/printThis#111]
Hello,

2 Days ago, I just Started to Work with this and Comparatively others, this is really awesome Library. But I found this Issue, ( Dunno whether this has been solved or Not ). That is the Content is not Broken into Multiple Pages according to the Page Size. The Print is always limited to the Content only to One Page.

Ex : 1. For the Page Size **A4** 
![fora4](https://cloud.githubusercontent.com/assets/7240672/26618120/95cfc28a-45f6-11e7-854c-03c0f9eab063.PNG)

It doesn't show the content which are lengthy from the A4 Size, and I took the print in real, It doesn't show the content. Means, It trim out the over Lengthy Part.

2. For Paper **Legal**
![forlegal](https://cloud.githubusercontent.com/assets/7240672/26618152/d1668ce8-45f6-11e7-9e0e-413926826a18.PNG)

For the Legal Page Size Whole Content Is Displayed. 

** The Actual Content I wanna Print is, as in the Legal Size Page**

So How Could I add Page Breaks, according to the Paper Size.

**Comment by oculus42** [comment]
Paged printing has a number of interesting headaches all by itself.

Does it print correctly without any styling? You can test this by adding the option `importCSS: false` and removing settings for `importStyle` and `loadCSS` if you set them.

If that works:

1. Do you use any `overflow:` settings on the content area you are printing? Can you remove/override them in an `@media print { … }` block, or in a print-only stylesheet?
2. Is this all one large table? Does it need to be?

If you are using Firefox, there are [dozens of known issues with printing](https://bugzilla.mozilla.org/show_bug.cgi?id=521204) that may be related.

Please refer to the [Issue Template](https://github.com/jasonday/printThis/blob/master/ISSUE_TEMPLATE.md) for the kind of information that makes it easer to help troubleshoot.

**Comment by TharakaMadhusanka** [comment]
I broke the page in to 2, purposely using **css Page-break-after/before** and now the print works in two pages ! But I found another issue there, that is CSS are loaded in the **LocalServer**, but css are not loaded in the **Azure Server**. Only CSS are not applied ! Any sense on that ? I am trying to fix that there in Azure server, but still couldn't find exactly a reason why it happens ! 

And CSS are applied , **borders and lines only but Colors are not applied**

And I am using external css, and I tried to apply @media print query but it is not Applied ! Rest of the CSS are applied but @media print is ignored ! 

I don't use any overflow : in CSS. And my whole content is inside a <div>, No <tables> . And I applied bootstrap Col-xs for every element as col-md , most of the bootstrap styles are not applied ! 

This is my suggestion on page-breaking, 
1. Get the content <div> Size ( Width & Length ) 
2. And add breaks and put the content to the pages, calculating with standard page sizes ( A4, A3, B1 etc. )

**Comment by jasonday** [comment]
1. Browser print does not print background colors by default and there's really no way to control it from the front end, as it is an option set by the user when printing. 
2. It is not possible to dynamically create breakpoints to print at specific page sizes. This is all user controlled within the user's print options. If you try to force users into specific paper sizes, what happens when a user wants to print in a different paper size? If you try to force the user down a path, you break the experience for a lot of other use cases.

**Comment by jasonday** [comment]
A potential solution here: https://stackoverflow.com/questions/16649943/css-to-set-a4-paper-size
Closing issue, as the mechanics are outside of the printThis plugin.
