### ISSUE TITLE
printThis where element is iFrame shows empty in Print Preview in Chrome

### ISSUE THREAD

**Issue by awilson69** [jasonday/printThis#112]
> short description of the bug / issue, provide more detail below.
I am working on a dashboard for a client, and for any widget on it which supports printing, I'd like to use the printThis library to do it. 

If the element that I pass contains inline html, then I have no problem.  But when the element I pass is an iframe, then nothing but a frame box appears in the Chrome Print Preview Window.

To reproduce, you can use the following test case:

element:
                    '<iframe src="http://www.msn.com"></iframe>'

printThis code:
                    contents = $(item.container).find("div.panel-body").clone();
                    $(contents).removeClass("panel-body");

                    $(contents).contents().printThis({
                        importCSS: false,
                        pageTitle: item.item.Name,
                        loadCSS: "http://netdna.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.css",
                        printContainer: true
                    });

====================================================================

###### `[  paste a link to an example (demo or active link) of the issue here ]`  

Your issue may be closed without active code to debug. Options include jsfiddle, jsbin, codepen, dropbox, etc. with code highlighting the specific issue you are having

====================================================================

#### Steps to reproduce the problem

1. ...  Include a div, with a child iframe on the page (see details above) and include a print button on the outer div.
2. ...  On Print, select the contents of that div and then use printThis(see details above) to print item.

====================================================================

#### What is the expected behaviour?

...  I'd like to see the contents of the iframe displayed, which the user can print.

====================================================================

#### What is the observed behaviour?

...  Iframe appears as an empty framed box in the preview window.

====================================================================

#### When you set `debug:true` and inspect the iframe, what do you see?

...  Nothing.  I don't see anything different at all.

====================================================================

#### More Details

- Which browsers/versions does it happen on? Chrome.
- Which printThis version are you using? 1.10.0
- Did this work before?  No.  This is my first time using this library.
![printthisiframeissue](https://user-images.githubusercontent.com/27510963/26990611-375c733e-4d25-11e7-9bb3-331ace2b8df3.png)

NOTE:
1.  The image I have included is split into two parts.  The top half is what I see in the Print Preview window, whether the debug feature is on or not.  The bottom half is the content that I'm trying to print , using the "print" button in the panel header.

**Comment by jasonday** [comment]
Answering from the hip, without research, my guess is that it won't work
with iframes. This is because printThis creates an iframe and copies over
the selector/contents to that iframe. Copying an iframe into an iframe is
likely causing issues. Set `debug: true`, inspect the page and find the
print iframe. Copy the contents and post them here.

**Comment by awilson69** [comment]
Thanks for replying so quickly, Jason.  I wasn't able to figure out how to copy the text of the iframe, so I took a screenshot of it and attached it below.  Let me know if there's anything else you need.

![printthisiframeissue2](https://user-images.githubusercontent.com/27510963/27031794-bc3229e8-4f3f-11e7-9c8f-9678f714213b.png)

**Comment by jasonday** [comment]
Can you expand #document and under that <html> within the iframe and post
the screenshot?

**Comment by awilson69** [comment]
Sure.  Here it is.
![printthisiframeissue3](https://user-images.githubusercontent.com/27510963/27036334-8862ac6a-4f52-11e7-9eee-630e298c7ceb.png)

**Comment by jasonday** [comment]
I need you to expand both <html>, <head>, and <body> within that iframe.
Thanks.

**Comment by awilson69** [comment]
I tried expanding the nodes like you asked for, but there's a ton of content.  At first guess, it looks like it would take a dozen screenshots or more to capture all that.  Is there something more specific I could grab?

In the interim, I found a work around that seems to work so far, but I've not fully tested it yet either.  Below is what I've done that appears to work:

                    contents = $(item.container).find("iframe");
                    contents[0].contentWindow.focus();
                    contents[0].contentWindow.print();

**Comment by jasonday** [comment]
I just wanted to confirm that the iframe had content, and your workaround
does indicate an issue with iframes if the selector is not the iframe
itself. This may not be something we can fix, but good information to have
either way. Thanks.

**Comment by oculus42** [comment]
This is a bit of a shot in the dark, but have you tried disabling the CSS using the option `importCSS: false` to see if you have some style that is interfering with the print?

**Comment by jasonday** [comment]
Closing issue; no further response.
