### ISSUE TITLE
Prepend or/and append html code to each page

### ISSUE THREAD

**Issue by FutoRicky** [jasonday/printThis#114]
First of all thanks for this library, awesome work. This is not an issue nor a bug, just a suggestion. It would be cool to have the ability to prepend or/and append html code to each page. Would love to contribute but I have no idea on how to approach this.

**Comment by jasonday** [comment]
> header & footer
> 
> A string or jQuery object to prepend or append to the printThis iframe content. null by default.
> 
> $('#mySelector').printThis({
>     header: "<h1>Amazing header</h1>"
> });
>  
> $('#mySelector').printThis({
>     footer: $('.hidden-print-header-content')
> });
>

**Comment by FutoRicky** [comment]
What I mean is to have it on each page, the existing header and footer is only showing once. The header is only on the first page and the footer only on the last page.

**Comment by jasonday** [comment]
Unfortunately, that's not achievable with any sort of consistency.

I would suggest trying one of several php>pdf based tools -
http://www.fpdf.org/
