### ISSUE TITLE
How to force/add class attribute to the BODY in the IFrame used for printing.

### ISSUE THREAD

**Issue by WzBn** [jasonday/printThis#118]
> Hi, It is not an Issue, it a question itself, Are any way of add class tribute information to the BODY in the IFrame used for Printing?

I am using to print part of a page , I'm using Metro boostrap so the BODY of the principal page has the class="metro" attribute, but this attribute it is not replicated to the BODY of the IFrame used.
As a result, grid system of metro it is not respected on the Iframe

I'm not and expert, sorry if the question it is irrelevant.

Thanks in advance for any help

Actual situation:
![captureprintthis001](https://user-images.githubusercontent.com/29458492/27925775-58d8c93a-625c-11e7-98e5-36a7c0edfa31.PNG)

Expected (adding class="metro" in Console )
![captureprintthis002](https://user-images.githubusercontent.com/29458492/27925776-58db05d8-625c-11e7-9036-15b7dbe756b8.PNG)

Js code calling the plugin

    $("[uc='rfsint']").printThis({
      debug: true,               // show the iframe for debugging
      importCSS: true,            // import page CSS
      importStyle: true,         // import style tags
      printContainer: true,       // grab outer container as well as the contents of the selector
      loadCSS: "",  // path to additional css file - use an array [] for multiple
      pageTitle: "EMI Visualizer_" + RFSID,              // add title to print page
      removeInline: false,        // remove all inline styles from print elements
      printDelay: 333,            // variable print delay; depending on complexity a higher value may be necessary
      header: "",               // prefix to html
      footer: "",               // postfix to html
      base: false,               // preserve the BASE tag, or accept a string for the URL
      formValues: true,           // preserve input/form values
      canvas: false,              // copy canvas elements (experimental)
      doctypeString: "",       // enter a different doctype for older markup
      removeScripts: false        // remove script tags from print content
    });

**Comment by oculus42** [comment]
An interesting problem. Not that this is a pretty solution, but I think you could solve it by injecting a script to the iframe content:

```
$(selector).printThis({
    footer: "<script>document.body.className += ' metro';</script>"
});
```

**Comment by jasonday** [comment]
Interesting issue that has come up before. I'm wondering if we should
include an option to preserve body classes?

**Comment by tmikaeld** [comment]
You really should, I had a similar problem where the body background was included and i needed it removed. This hack solved this issue 👍
