### ISSUE TITLE
Not work for canvas printing

### ISSUE THREAD

**Issue by abramhum** [jasonday/printThis#124]
I use pdf.js to show the pdf online, and it store the data in canvas element.
When I use $('#canvasid').printThis(), I get an empty page. 
the following is the codesnippet:

JAVASCRIPT:
    <script type="text/javascript" src="./../jsfiles/pdfviewer/pdf.js"></script>
    <script type="text/javascript" src="./../jsfiles/pdfviewer/view.js"></script>
    <script type="text/javascript" src="./../jsfiles/pdfviewer/printThis.js"></script>
    <script type="text/javascript">
        PDFJS.workerSrc = './../jsfiles/pdfviewer/pdf.worker.js';
        PDFJS.getDocument('https://cdn.rawgit.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf').then(function (pdf) {
                   pdf.getPage(1).then(function (page) {
                    var canvas = document.getElementById('canvasid')
					var scale = 2.5;
                    var viewport = page.getViewport(scale);  
                    var context = canvas.getContext('2d');
                    canvas.style.height = "1000px";
                    canvas.style.width = "900px";
                    canvas.height = viewport.height;
                    canvas.width = viewport.width;
                    var renderContext = {
                        canvasContext: context,
                        viewport: viewport
                    };
                    page.render(renderContext);
                });
        })
		
		
		
        function PrintThisCancas()
        {
            $('#canvasid').printThis();
        }

</script>

HTML:
        <div>
            <input type="button" onclick="printCanvas('canvasid')" value="print a canvas!" />

            <div id="pdf-container" style="width: 800px; height: 1000px; text-align: center;">
                <canvas id="canvasid"></canvas>
            </div>

        </div>

Thanks a lot

**Comment by jasonday** [comment]
If you're creating a pdf, why do you need printThis? Can't a pdf be generated in a new tab, allowing the user to print using native print functionality?

**Comment by oculus42** [comment]
Canvas support is **disabled by default** as it is still considered experimental – we just haven't had enough time & variety to say that it absolutely works.

Use `$(…).printThis({canvas: true});`

**Comment by oculus42** [comment]
@abramhum Did you have any luck with the `{canvas: true}` setting?

**Comment by abramhum** [comment]
None, there encounter an error message. 
The problem come from followings:
`  this.getContext('2d').drawImage($src[0], 0, 0);`
is PrintThis can print all canvas under one element like <div> in future, thanks

**Comment by oculus42** [comment]
I was looking over your issue and realized that the canvas logic never expected the canvas element to be the only thing being printed. Can you try printing a `<div>` or a container around the canvas element?

**Comment by abramhum** [comment]
I try and found it can work.
But still have an problem that is the DPI seems changed when printing.
Is that means I should modify the codes in PrintThis library,
and thanks again

**Comment by oculus42** [comment]
We haven't tested the Canvas behaviors that closely, which is while it's still considered Beta. There may be something we can do to improve the resolution of a copied canvas, but I am not sure.

**Comment by oculus42** [comment]
@abramhum Have you tried something like setting up a "HighDPI canvas"?

https://www.html5rocks.com/en/tutorials/canvas/hidpi/

**Comment by jasonday** [comment]
@abramhum - did you print without printThis to see if the DPI change is due to printThis or inherent tp printing?

**Comment by oculus42** [comment]
It's been ~90 days since the last response. Closing the ticket. Please re-open or create a new ticket for the DPI issues if they persist.
