### ISSUE TITLE
Force resize to page ?

### ISSUE THREAD

**Issue by XanderCam** [jasonday/printThis#125]
I would love a simple setting to allow the script to resize the content to "fit to page".
I know the user may choose to resize ot change settings manually, but I would like to set it 
as a standard.

And / Or forced "page split" would be nice.

**Comment by oculus42** [comment]
I'm not sure I understand the suggestion.

Are you saying the script should be able to adjust the content size to the printed paged? If so, I do not believe this can be reasonably accomplished within the browser, and you might consider something like [jsPDF](https://github.com/MrRio/jsPDF).

There is no way to know the page size before printing, and once the print dialog is open, the script is paused.

You can use `@media print` CSS or even create a stylesheet just for your printing needs  to accomplish some or all of this. Both of these are currently supported.

There are also some CSS settings for page breaks, but they are inconsistently implemented/supported across browsers.

**Comment by oculus42** [comment]
@jasonday Anything we can add to this?

**Comment by jasonday** [comment]
@oculus42 - I don't think there's anything we can do within reason to address this type of issue.

**Comment by jasonday** [comment]
Closing issue; unable to implement request.
