### ISSUE TITLE
How to Scale the result image to A4 size

### ISSUE THREAD

**Issue by abramhum** [jasonday/printThis#126]
> short description of the bug / issue, provide more detail below.

====================================================================
Using  ` $('#pdf-container').printThis({ canvas: true })` and then the result not the A4size

issue:
I using printThis, and use the upper instruction to print the canvas, and then , it success, but 
the image size can not be designate to A4 size.  I look inside the codes, and found the code snippet
`  this.getContext('2d').drawImage($src[0], 0, 0);`. And the problem is, if I hope to fit the result 
to A4 size, how could I do, thanks.

**Comment by abramhum** [comment]
I have tried add codes in line 205, `this.classname += "mainCanvas";`, and add an css file which its content 
is `@media print {
    .mainCanvas {
        width:100%;
       height:auto;
    }
}`

And set the printThis as following:
` $('#pdf-container').printThis({ canvas: true, loadCSS: ["./../cssLibary/printThis.css"] });`
and the result is fail, after trace the codes, I found the css not included in, and fail, that's strange, 
it fail at domManip function with `target.appendChild( elem );`  instruction in jquery.
Is that a problem of printThis library, how to fix it and add a css file to that, thanks.

**Comment by oculus42** [comment]
You should not need to edit the library to accomplish your goals. Just add the class to the original page so your print CSS works as expected.

As for the loadCSS, try an absolute path (beginning with the original `/` from the domain). This code will be loaded in an iframe, not the current page, and so it will not have the same current path for relative URLs like `./../`

**Comment by abramhum** [comment]
it work great in chrome, thanks a lot.

**Comment by oculus42** [comment]
Yeah, print is very inconsistent. You might try in a print CSS file setting a specific size for IE only. It looks like a very specific media query that can work on it.

- [Media Query for IE 10 & IE 11 Only](https://paper-leaf.com/blog/2014/09/targeting-ie-10-11-browsers-css/]

Do we need to keep this issue open?

**Comment by abramhum** [comment]
No, thanks a lot for your help.
