### ISSUE TITLE
wrong font on print preview and printed media

### ISSUE THREAD

**Issue by dirtgambitcp** [jasonday/printThis#127]
Hello, We have a special font we need for displaying symbols, in the modal window the symbols appear fine, when I right click and print the window normally the symbols appear on the print preview, when I use printthis the symbols are gone and replaced with weird ones, ive tried loadcss, different combinations of importStyle and loadCss. it just seems the actual font isn't being picked up by print preview. ive attached 2 images, print raw is what I see in the div that I'm trying to print, print preview is what I see in the preview (is slightly bad quality but the symbols arnt there)

Kind regards

![printraw](https://user-images.githubusercontent.com/31621224/30026094-5fbcd958-9173-11e7-91bd-e9381219f79f.png)
![printpreview](https://user-images.githubusercontent.com/31621224/30026102-64b516aa-9173-11e7-8117-3d0f4a11da0a.png)

**Comment by oculus42** [comment]
This may be due to the URL/path of the font in the CSS. Because the printThis iframe doesn't share the same path as the page. You might try using an absolute path or a fully-qualified URL for the font. You could do this in a CSS file just for print.

**Comment by oculus42** [comment]
@dirtgambitcp Any follow-up on this? It's been over a month.

**Comment by jasonday** [comment]
Closing issue; no further response.
