### ISSUE TITLE
Update npm

### ISSUE THREAD

**Issue by stritti** [jasonday/printThis#128]
> Version on npm is outdated.

====================================================================

###### [https://www.npmjs.com/package/printthis](https://www.npmjs.com/package/printthis) 

====================================================================

#### Steps to reproduce the problem

1. use `npm install printthis` in your project.

====================================================================

#### What is the expected behaviour?

Current version 0.1.9 should be available.

See at [https://docs.npmjs.com/getting-started/publishing-npm-packages](https://docs.npmjs.com/getting-started/publishing-npm-packages) for getting started.

====================================================================

#### What is the observed behaviour?

Version 0.1.5 is installed.

**Comment by oculus42** [comment]
Please use `print-this` which is updated. We are not in control of the `printthis` package.
https://www.npmjs.com/package/print-this

**Comment by stritti** [comment]
Thank you very much! 
Could you add a reference to readme? Would be great: [https://github.com/erming/npm-badge](https://github.com/erming/npm-badge)

**Comment by oculus42** [comment]
Readme reference added to clear up confusion. @stritti Please comment if you feel we need to reopen this issue.
