### ISSUE TITLE
use printThis in Ionic-Angular

### ISSUE THREAD

**Issue by Rehan1579** [jasonday/printThis#130]
Hi.

This is not an issue but a humble request actually. I want to use your plugin and I'm a newbie in Web. I've tried to use your plugin on my own but i couldn't make it work. I tired asking in Ionic forum but they didn't help me at all but saying don't use jquery plgins, find alternate ways etc. You can check yourself.

https://forum.ionicframework.com/t/use-jquery-plugin-in-ionic/102537

I really need to use this plugin in my project. if you could tell me a way how to do it or make very small Ionic project or whatever you feel easy.

Kindly, help me out.

**Comment by italoportinho** [comment]
Hi there.

Make sure your code is running after both jquery and printThis has loaded.

But in the link you provided, they already told you that Angular and Jquery
does not work well together.

**Comment by jasonday** [comment]
@Rehan1579 any update?

**Comment by Rehan1579** [comment]
@jasonday yes, i made it work but i faced some other issue. No matter what i do, it just prints single page. Consider it half useful (in my case). it prints but only 1st page. 

I don't know whether its the library or the frameworks(Angular-Ionic) i'm using, causing this conflict!!!
Left with no choice i then had to hire someone so he could provide me with some online library for printing and it worked great (printing multiple pages)

plz, help me in this regard, you can have my code if you want to ? 
Totally helpless.

**Comment by jasonday** [comment]
@Rehan1579 Is the section/element of what you want to print large, or contain a lot of data? My guess is that the html in the print iframe needs more time to render. Try using the option printDelay by increasing the time to see if that resolves your issue.

**Comment by oculus42** [comment]
@Rehan1579 I've Started a wiki page with some common troubleshooting notes that may help:

https://github.com/jasonday/printThis/wiki/Troubleshooting-Printing-Problems

**Comment by jasonday** [comment]
No further updates. Closing.
