### ISSUE TITLE
Plugin not working in iPad

### ISSUE THREAD

**Issue by ijaidka** [jasonday/printThis#132]
Hi,

I tried to use this plugin, but it does not works with iPad. It works fine for Laptop, Desktop but not with iPad. I am using Google Chrome as a browser in iPad.
Any help will be much appreciated.

Thank You.
Kind Regards.

**Comment by jasonday** [comment]
From the readme and in the issue template:

> - "It's not working" without any details is not a valid issue and will be closed
> - A url, or html file, is necessary to debug. Due to the complexities of printing and this plugin, an example is the best way to debug
> - When troubleshooting, set debug: true and inspect the iframe. Please report your findings when reporting an issue
> - Every user should be active in the debugging process

**Comment by jasonday** [comment]
Closing issue; no details.
