### ISSUE TITLE
Apply styles to element to print

### ISSUE THREAD

**Issue by ArkhamEng** [jasonday/printThis#135]
Hello I triying to print a div with some content in it, but i cannot set a custom font size. Can you tell me how can I change the font size and font color please?

**Comment by jasonday** [comment]
* [LoadCSS](https://github.com/jasonday/printThis#loadcss)
* [Styling Printed Content](https://github.com/jasonday/printThis/wiki/Styling-Printed-Content

**Comment by ArkhamEng** [comment]
thank you very much

**Comment by jasonday** [comment]
@ArkhamEng - No. Those are all user controlled settings that we do not have access to.
