### ISSUE TITLE
Support canvas as top-level element

### ISSUE THREAD

**Issue by oculus42** [jasonday/printThis#136]
If selecting only a `<canvas>` element on the page and not a containing `<div>`, the canvas copy may not throw an error.

====================================================================

#### Steps to reproduce the problem

`$('canvas').first().printThis();`

====================================================================

#### What is the expected behaviour?

As a developer, I should be able to print just a `<canvas>` element.

**Comment by jasonday** [comment]
I assume this is true of you use a class or id on the canvas element and use that as a selector?
