### ISSUE TITLE
how to print a <div> with background image?

### ISSUE THREAD

**Issue by MRSheikh** [jasonday/printThis#140]
i want to print my div with background image. i set "importStyle: true" but nothing happened.

## <div id="divPrint" class="form-group" style="background-image: url('<%=ResolveUrl("~/desktopmodules/turnrating/image/dadsara.jpg")%>'); background-position: top; background-repeat: no-repeat; background-size: 100%;">

</div>

and my script is below:

        $("#divPrint").printThis({
            pageTitle: "jQuery printThis Demo",
            importStyle: true,
            header: "",
            footer: ""
        });

**Comment by oculus42** [comment]
We've added information to the Wiki on this topic:
https://github.com/jasonday/printThis/wiki/Styling-Printed-Content#printing-backgrounds

**Comment by oculus42** [comment]
`importStyle` is for copying `<style>` tags, which is not the case, here. You are using inline styles, which are represented. Backgrounds just don't print by default, regardless of the printThis plugin.

That can be overridden in some browsers, or you may need to enable background printing once the print dialog is opened.

**Comment by MRSheikh** [comment]
> importStyle is for copying <style> tags, which is not the case, here. You are using inline styles, which are represented. Backgrounds just don't print by default, regardless of the printThis plugin.

thanks a lot oculus42. 
i use `<img>` tag instead of background-image and set z-index=-1 then print it.
`
<img alt="" src='<%=ResolveUrl("~/desktopmodules/turnrating/image/dadsara.jpg")%>' style="z-index: -1; position: absolute;"/>
`

**Comment by oculus42** [comment]
Glad to help @MRSheikh 
Are we OK to close this issue?

**Comment by MRSheikh** [comment]
hi. yes i solved my issue with your clue !!!
thanks.
