### ISSUE TITLE
<style> tag cannot be easily cloned

### ISSUE THREAD

**Issue by futurist** [jasonday/printThis#142]
> short description of the bug / issue, provide more detail below.

[this line](https://github.com/jasonday/printThis/blob/40f8ebed2d85953c0191ea486b6ecdc844de6596/printThis.js#L169) of clone <style> may cause bug if the [style rules is inserted using js](https://davidwalsh.name/add-rules-stylesheets)

#### Steps to reproduce the problem

1. open your console, select any <style> tag in [this page](https://cssobj.github.io/cssobj-demo/)
2. $($0).clone(), or `$0.cloneNode(true)`

#### What is the expected behaviour?

The cloned node should have right stylesheet.

#### What is the observed behaviour?

You cannot clone any `<style>` tag in this page
The cloned node don't have text of dynamically inserted.

====================================================================

#### When you set `debug:true` and inspect the iframe, what do you see?

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which printThis version are you using?
- Did this work before?

I've created [clone-style](https://github.com/futurist/clone-style) to help.

**Comment by oculus42** [comment]
I made a small test and can confirm that our style tag is not being cloned as expected.

**Comment by jasonday** [comment]
@oculus42 is this a bug or feature request? In reading through, I'm thinking there are other methods (`loadCSS`, a print stylesheet) that would work as a workaround?

**Comment by oculus42** [comment]
This is a bug. In my quick tests, the `importStyle` function doesn't work.

**Comment by jasonday** [comment]
We'll have to make a change here. In quick testing, it looks like we can use:
`document.getElementsByTagName("STYLE");`, which does return all of the `<style>` elements in the document.

**Comment by jasonday** [comment]
In my quick tests, this seems to work:
```
$('body').append('<iframe id="test"/>');
var styles = document.getElementsByTagName("STYLE");
$("#test").contents().find("head").append(styles);
```

**Comment by oculus42** [comment]
This works, but has the same problem we previously solves with accidentally removing header content from the original page.

I am working on a solution, but IE has some complex limitations.

**Comment by oculus42** [comment]
I have a test up at https://jsfiddle.net/strg7k4u/14/  and will see about IE compatibility.

**Comment by oculus42** [comment]
I forgot JSFiddle doesn't support older IE anymore. Switched to CodePen: https://codepen.io/_sir/full/eMZqrZ/

**Comment by oculus42** [comment]
I can confirm it works on IE 9, 10, and 11, as well as Safari on Desktop. Codepen won't let me print from the iframe on my iPad. Trying JSFiddle.

**Comment by oculus42** [comment]
Confirmed the ability to print successfully in IE 9+, Chrome, Firefox, Safari on desktop and iOS, without impacting the original document. v1.12.3 has been published.

**Comment by jasonday** [comment]
Thanks Sam.
