### ISSUE TITLE
Header disappears

### ISSUE THREAD

**Issue by rbasw-mbrandel** [jasonday/printThis#143]
When using header: $('.classname') option my header disappears.

$('.wo-print-btn').click(function () {
                console.log('Print Clicked');
                $('main').printThis({
                    debug: false,
                    header: $('.navbar-header')
                    //loadCSS: "path/to/my.css",
                 });
            });

The header I'm using is on the page itself. It display's fine in the print window/document but also seem to disappear from the browser itself??

- Chrome
- printThis v1.9.0

**Comment by oculus42** [comment]
What version of printThis are you using?

Prior to 1.12.0, the `header` option expected to receive a string, so it would just append the content to the form, causing this bug.

If you upgrade to a more recent version of printThis, it should not happen.

If that is not possible/convenient, you can call it this way:

```javascript
printThis({
  header: $('.navbar-header').clone()
});
```

**Comment by rbasw-mbrandel** [comment]
Thanks the clone option worked great!
