### ISSUE TITLE
Printing Multiple Elements Does Not Work

### ISSUE THREAD

**Issue by zendog74** [jasonday/printThis#145]
Description of issue:
Cannot print multiple elements.

Both elements exist and the selectors are correct. I have tried putting the selectors in directly and using variables. I even tried putting both selectors into a single string and appending single quotes at the beginning and end of the string, as is seen in the example of how to print multiple elements.

The 2nd element is a table. However, I tried wrapping the table in a div and referencing it instead and it did not work either.

I also tried making the printDelay = 999 to give the iframe more time to be populated and it did not work.

self.uid = a unique string.

====================================================================

Code & options:
```
//Example:
var sel1 = "#eventListTable"+self.uid;
var sel2 = "#calendarLegend"+self.uid;
jQuery(sel1, sel2).printThis({
    printDelay: 333,
    removeScripts: true
});
 ```

**Comment by jasonday** [comment]
I guess my first questions are:

* how/when is the unique string generated?
* have you confirmed that the selectors are the same as what's generated in the DOM? An easy test is to pick elements that do not have a unique string, and test if printing multiple is indeed broken.

**Comment by oculus42** [comment]
Passing two arguments into jQuery is not the same as passing two selectors in a string.

Try `$(sel1).add(sel2).printThis(...)` or `$('sel1 + ', ' + sel2).printThis(...)`.

**Comment by jasonday** [comment]
Good catch.

>

**Comment by zendog74** [comment]
Indeed, I was able to get it to work by constructing a CSV string and passing it in.

```
var sel = "#eventListTable"+self.uid+","+"#calendarLegend"+self.uid;
jQuery(sel).printThis({
    printDelay: 333,
    removeScripts: true
});
```
Having each selector quoted separately will not work.
