### ISSUE TITLE
Bootstrap table print issue

### ISSUE THREAD

**Issue by YuTingLiu** [jasonday/printThis#147]
How to print a table with style in bootstrap, especially with the ## border of the table.

this script comes from your demo page.
thx.
====================================================================

                    $('#advanced').on("click", function () {
                        $('#table2print').printThis({
                            importCSS: true,
                            importStyle: true,
                            removeInline: false,
                            loadCSS: "{% static 'css/bootstrap.min.css' %}",
                            header: "<h1>Look at all of my kitties!</h1>",
                            base: "https://jasonday.github.io/printThis/"
                        });
                    });

**Comment by oculus42** [comment]
Start with the basic printThis command:

```javascript
$('#advanced').on("click", function () {
    $('#table2print').printThis();
});
```

Or try fewer options:

```javascript
$('#advanced').on("click", function () {
    $('#table2print').printThis({
        importCSS: true,
        importStyle: true,
        removeInline: false
    });
});
```

**Comment by YuTingLiu** [comment]
@oculus42 :thx, may be next time i will use this tools
