### ISSUE TITLE
how can I remove datetime and link path from print page?

### ISSUE THREAD

**Issue by webcoweb** [jasonday/printThis#149]
Hello
how can I remove datetime and link path from print page?

**Comment by jasonday** [comment]
This is the default print behavior for the browsers, so printThis doesn't provide any methods for overriding, but you may be able to do this with CSS:

`@media print {
   @page 
        {
            size: auto;   /* auto is the current printer page size */
            margin: 0mm;  /* this affects the margin in the printer settings */
        }
}`

I haven't tested this myself, so let me know if it works for you.

**Comment by oculus42** [comment]
No follow-up after two months. Closing. Please re-open if you require additional assistance.

**Comment by daniellizik** [comment]
https://stackoverflow.com/a/14975912/4769440
