### ISSUE TITLE
Background color, I think i narrowed down the problem

### ISSUE THREAD

**Issue by khaledman09** [jasonday/printThis#151]
Description of issue:
Browser = Chrome.
The main issue is with the TD/TH element's background-color not showing when printing (even when switching to color mode on printer settings).
After some analyzing, I think i narrowed down the problem: I found that some elements do preserve their background colors and some don't, for example the element "button" does preserve it's background color, but "td" and "th" don't, I can do a workaround of fashioning the "td" element so it does have a "button" inside it, but I rather find a correct solution.

====================================================================

**Comment by khaledman09** [comment]
I found a better workaround, apparently <div> preserve it's background color too, so I just put a <div> inside a <td>

**Comment by oculus42** [comment]
I don't believe this is unique to printThis, but rather a problem in general with printing backgrounds.

We do have a [small section in the Wiki on printing backgrounds](https://github.com/jasonday/printThis/wiki/Styling-Printed-Content#printing-backgrounds) which may be useful.

**Comment by jasonday** [comment]
@khaledman09 any further update? Is your issue resolved?
