### ISSUE TITLE
Printing on firefox not working as expected

### ISSUE THREAD

**Issue by FutoRicky** [jasonday/printThis#154]
Description of issue:

This issue I am only experiencing on FF. I am trying to print a div that contains two `h3` and a table. When It prints it leaves out a blank space on the whole page after the `h3` headers, and continues on the 2nd page. The content on the 2nd page is cut and does not continue on a new 3rd page.

====================================================================

Code & options:

I'm just calling printThis on the div's id.

```
Ember.$('#profitLoss').printThis()
 ```

**Comment by jasonday** [comment]
My guess is that you're running into an issue with a float on one of the containers (such as the table) that's causing an incorrect print.

Try setting `debug:true` and inspecting the iframe and/or try adjusting the CSS around the `#profitLoss` container or child table to correct the issue.

**Comment by FutoRicky** [comment]
I tries setting `debug: true` and it looks fine on the iframe, it's just when it prints that the issue happens.

**Comment by jasonday** [comment]
It sounds as though the table doesn't want to break, so it is printing onto a second page.
You can try to set `importCSS` to `false` to see if that resolves the issue, as you may have CSS that's causing the print problem. 

Additionally, you can also try to add to your CSS:
`table { page-break-inside:auto }`

**Comment by FutoRicky** [comment]
Tried both and still the same issue... It surely is a weird issue, for now I'll find another way to print since for this case I'm unable to use the library. I'm still using it for other cases though. Thanks for the work.

**Comment by jasonday** [comment]
I am fairly certain it is CSS driven and can be corrected. If you would like another set of eyes on it, please let me know where I can see the issue.

**Comment by oculus42** [comment]
Closing three months later. Please re-open if there is additional activity on this issue.
