### ISSUE TITLE
Saving as a pdf (immediate download)

### ISSUE THREAD

**Issue by darron1217** [jasonday/printThis#155]
Description of issue:

I'm currently using this fancy plugin :)
But I wondered if there's a proper way to print as a pdf without printing dialog

This plugin seems to use `iframe`. Is there a way to get html data of it? If then, maybe I can put the contents to canvas and make it as a pdf.

**Comment by jasonday** [comment]
You could alter the plugin to suit your needs, but there are other plugins that might be more suitable. That said, we'll take it into consideration as a future effort to include support for a pdf generation library.

**Comment by darron1217** [comment]
@jasonday That sounds great :)
I searched for similar plugin, but none of them could handle CSS on print view.

**Comment by AhmedNourJamalElDin** [comment]
+1

**Comment by alex78420** [comment]
Any info on a future update about direct download ?

**Comment by jasonday** [comment]
@alex78420 at this time, it's not planned for.

**Comment by alex78420** [comment]
Thx for this quick answer and this useful library 👍,  do you know the best alternate library for direct download and keeping the logic of this library's way of handling CSS ?
