### ISSUE TITLE
How to show preview for firfox (61.0.1) ？

### ISSUE THREAD

**Issue by fmpoffice** [jasonday/printThis#158]
Description of issue:
I use Google Chrome  is ok  to show preview 👍 
![360](https://user-images.githubusercontent.com/11001031/43076646-741f02f8-8eb7-11e8-9898-7a71702cf567.png)

BUT,  Firfox is call system printing function：
![sougou](https://user-images.githubusercontent.com/11001031/43076704-a1aac856-8eb7-11e8-917e-17d0c202c959.png)

====================================================================

Code & options:
```
//Example:
    	$('#stockOutTable').printThis({
    		importCSS: true,            // import page CSS
    		importStyle: true
    	});
 ```

**Comment by jasonday** [comment]
> Print Preview has been the "go to" action in Firefox for quite awhile now, at least since Firefox 29 and possibly before - when you use the Toolbar button  which is hidden in the UI by default.
Source: https://support.mozilla.org/en-US/questions/1215520

That said, I'm not sure if there is currently a method to invoke the print preview.

**Comment by oculus42** [comment]
Agreed. This is browser behavior that takes place outside of JavaScript. [Print Preview cannot be invoked by JavaScript in Mozilla browsers](https://support.mozilla.org/en-US/questions/948326)
