### ISSUE TITLE
How to set header/footer to all pages?

### ISSUE THREAD

**Issue by albertml** [jasonday/printThis#159]
This is my code
   
$('#btnPrint').click(function () {
            $("#mybody").printThis({
                debug: false,
                importCSS: true,
                header: $('#myheader'),
                footer: $('#myfooter'),
                copyTagClasses: true,
                printContainer: false,
                loadCSS: [
                    "styles/mystyle.css"
                ],
            });
        })

**Comment by oculus42** [comment]
The ability to add a header and footer to a page is not consistently supported across browsers, but in *some* browsers, it is possible to use some complex CSS to produce repeated headers and footers. Solving the issue of content overlapping is another matter. 

This is a concern for *all* printing, not just printThis, and unfortunately there does not appear to be a good solution.

**Comment by jasonday** [comment]
Closing
