### ISSUE TITLE
Trouble importing/loading any type of styling

### ISSUE THREAD

**Issue by drkrtj** [jasonday/printThis#160]
Description of issue:

    Hello, I love this print script. It is by far the best I've tried. I am however having some trouble. Obviously I am the problem. I am a js newbie.
    I am successfully able to get the printThis script to work. I am however completely unable to get any styling to accompany the print. I am printing to adobe pdf and I am getting bullets before each field due to my unordered list items. Of course my css has text-decoration set to none. 
    In loadCss I have placed the link in many different ways/orders/double quotes outside/double quotes inside....etc but I am to no prevail. Currently it is set to that below.

userprint.css was specially made just for printing the printThis form. I would definitely appreciate any assistance to show what I am doing wrong and how to correct my mistakes.
Thanks
Here are my current settings:
      
====================================================================

Code & options:
```
"<link type='text/css' rel='stylesheet' href='css/userprint.css' media='all'/>"



                        debug: false,               
			importCSS: true,            
			importStyle: true,        
			printContainer: true,
			loadCSS: "<link type='text/css' rel='stylesheet' href='css/userprint.css' media='all'/>",Mail this Form",   
			removeInline: false,        
			removeInlineSelector: "*",  
			printDelay: 333,           
			header: "<h1>Mail This Page</h1><br><h3>Confirm all information is correct before sending</h3>",     
			footer: null,               
			base: false,                
			formValues: true,           
			canvas: false,              
			doctypeString: '<!DOCTYPE html>',       
			removeScripts: false,       
			copyTagClasses: false,      
			beforePrintEvent: null,     
			beforePrint: null,          
			afterPrint: null  
 ```

**Comment by jasonday** [comment]
Add the fully qualified path (url) to the loadCSS option.

**Comment by drkrtj** [comment]
Thanks for the reply. I am starting at my root folder (root/css/userprint.css). Are you referring to the pc's folders holding my root folder on my local host...such as

C:/Users/CurrentUser/Desktop/websitefiles/css/userprint.css'> ?

Can you give me an example?
     Thanks

**Comment by drkrtj** [comment]
.....which neither works by the way.

**Comment by oculus42** [comment]
@drkrtj did the fully qualified url help?

**Comment by oculus42** [comment]
You should be able to add a media query to eliminate the bullets. Something roughly like this:

```CSS
@media print {
  ul { list-style-type: none; }
}
```

**Comment by drkrtj** [comment]
Hello,
    I put this into the parent css and the import css. However, nothing shows up on the pdf.

@media print {
	.printedform_text {
		text-decoration: none!important;
		list-style: none!important;
		font-size: 80px;
		color: red;
	}
}


         Thanks for your assistance

--------------------------------------------
On Fri, 8/17/18, Samuel Rouse <notifications@github.com> wrote:

 Subject: Re: [jasonday/printThis] Trouble importing/loading any type of styling (#160)
 To: "jasonday/printThis" <printThis@noreply.github.com>
 Cc: "drkrtj" <drkrtj@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Friday, August 17, 2018, 12:27 PM
 
 You should be able to add a media
 query to eliminate the bullets. Something roughly like
 this:
 @media print {
   ul { list-style-type:
 none; }
 }
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by jasonday** [comment]
Are you printing to pdf?

**Comment by drkrtj** [comment]
Hello,
    Yes, currently I am . 

           
--------------------------------------------
On Fri, 8/17/18, Jason Day <notifications@github.com> wrote:

 Subject: Re: [jasonday/printThis] Trouble importing/loading any type of styling (#160)
 To: "jasonday/printThis" <printThis@noreply.github.com>
 Cc: "drkrtj" <drkrtj@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Friday, August 17, 2018, 7:26 PM
 
 Are you printing to pdf?
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by oculus42** [comment]
If you add the option `debug: true` and look at the iframe added to the page, do you see the bullets there?

What do you have for the `loadCss` value, now? It should be something like `'http://www.mysite.com/css/userprint.css'`

**Comment by jasonday** [comment]
@drkrtj  any further update on this issue?
