### ISSUE TITLE
prevent a specific class from being printed

### ISSUE THREAD

**Issue by itsmekps** [jasonday/printThis#161]
I want to hide a column of the table from being printed. Is it possible to do so ?? I tried by giving a class to that td `<td class="ret">` but unable to hide from all the rows of the table just `<th class="ret">` got restricted from printing but all the td with class ret got printed.

**Comment by oculus42** [comment]
You can specify styles in the `<thead>` element using the `<col>` and `<colgroup>` which may allow you to hide a column. I have not validated this.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col

**Comment by itsmekps** [comment]
thanks a lot for your reply, i have achieved the solution by @media print
