### ISSUE TITLE
When page is in the iframe its not woking in ipad chrome.

### ISSUE THREAD

**Issue by swsatheesh** [jasonday/printThis#165]
Description of issue:
I have tried this in my project. I think its not working when page is in the iframe.
This issue only occurs in the ipad chrome.

Here is the best example, below link doesn't work in the ipad chrome. Bcoz the output area is in the iframe.
[Link](https://jsfiddle.net/7uwm8sd0/85/)

**Comment by oculus42** [comment]
Are you trying to print an area inside an iframe on your page? Unless you have the same origin on that iframe, you would. It be able to access the document inside the frame, for security reasons.

I don’t think jquery will walk into another document by default.

**Comment by swsatheesh** [comment]
Yes I'm trying to print an area inside an iframe. But, trying to print from the iframe.

Go to that fiddle link and see that in the developer tool, you can find 'Jquery' and 'printThis' package links in the iframe. I think this answers your question and jquery walking into another document.

If it is a same origin issue then how it is working in ipad safari and ipad firefox but not in ipad chrome.

I think this issue is not in this package. It's an issue from the ipad chrome. I have spend an entire day on this issue. still can't find the answer. It seems link this issue is always in there. Right now I'm trying to figure out whether it can be fixed or not.
