### ISSUE TITLE
Trigger after print...

### ISSUE THREAD

**Issue by danyg790** [jasonday/printThis#173]
Description of issue:
Is there a way to trigger an event after print? So Upon print completion call a function to do something... If print canceled do nothing. 

====================================================================

Code & options:
```
//Example:
$('#myDiv').printThis({
   importCSS: false
});
 ```

**Comment by caseyjhol** [comment]
See `afterPrint`.

> Function called after the print and before the iframe is removed from the page.
This is called even if `debug: true`, which does not remove the iframe.

**Comment by oculus42** [comment]
Once the print action starts, I do not believe there is a way to determine if it was cancelled. Per MDN's [`onafterprint` page](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onafterprint):

> These events are raised after the user prints, or if they abort the print dialog.

**Comment by danyg790** [comment]
Ok, so I want it to only trigger if they print, if they cancel I want to do nothing... Is there a way to do that?


Daniel James G


-------- Original message --------

**Comment by danyg790** [comment]
Is there a way that element.printThis() can have a return value of true or false whether the element gets printed or not? 
example if( element.printThis() ){
   do something...
}

**Comment by jasonday** [comment]
As @oculus42 states above, once the print process is started, the activity is obscured - meaning, there's not currently a way to know the action the user took (print/cancel).

**Comment by danyg790** [comment]
Ok, thanks for you help.
