### ISSUE TITLE
Printing full element(A4 size)

### ISSUE THREAD

**Issue by constmoon** [jasonday/printThis#174]
Description of issue:

Hi. 
I have set the div's css to A4 ratio (1:1.4142) to match the real A4 size.
When it was printed, I expected my div to be full of A4.
But when I press the print button, it creates an unknown margin, rather than a full screen.
I'll attach the [code](https://codepen.io/constmoon/pen/JzKMjO).
How should I set up to be printed full on the actual A4?

**Comment by constmoon** [comment]
I solved it by myself... Modify the css which is importing before prints.
```
*{
    margin: 0;
    padding: 0;
}
@media print{ 
    @page { 
        size: a4; 
        page-break-after: always; 
    }
    body { 
        margin-left:-250px; 
        border:0; 
        padding:0; 
        width: 210mm; 
        height: 297mm; 
    }
    #field { 
        width: 100%; 
        height: auto;
        position: absolute;
        top: 0;
    } 
}
```
And import it before printing.
```
$('#field').printThis({
    importCSS: true,
    loadCSS: "print.css",
});
```

**Comment by jasonday** [comment]
In looking at your code, you have:
`height: calc(60vh * 1.414285714);`

So, that's saying 60% of vertical height  * 1.4.14, which equals 84.84% of the vertical height, which if I add a border to `#field`, I can see that it is working as expected.

If I add the following, the print basically fills the page (a little bit beyond as I believe the header/footer print elements are affecting the measurement)

```
@media print {
  #field {
    height: 100vh;
    border: 1px solid #000;
  }
}
```
