### ISSUE TITLE
Print issue 

### ISSUE THREAD

**Issue by sai78** [jasonday/printThis#177]
I am having a div element and a button as child to that div element. When I click on the button it should print the div element. The div element can be drag-able with mouse when I drag the div element down to the screen then print also giving empty space with the div element is showing down. Is there any way to set whatever the position of the div element the print page should start from the top of the page? Thanks in advance.

**Comment by jasonday** [comment]
Without seeing code, it's impossible to troubleshoot the issue. That said, my guess is that when the element is dragged to a new position, there's CSS added to 'place' that div element in a specific location. Using the `removeInline: true` attribute should solve that issue (if that's what it actually is).

In the future please provide an example to work from.

**Comment by jasonday** [comment]
Any further update?
