### ISSUE TITLE
Image not printing

### ISSUE THREAD

**Issue by pithhelmet** [jasonday/printThis#178]
Created a DIV to print.  
Loaded the content of the DIV.
Added a canvas into the contents of the DIV within a table.

Loaded the canvas with a image grabbed from the laptop camera.

Button click to print the DIV.

Everything EXCEPT the canvas was printed.

`                      <div class="demo"  id="toPrint">
                        <table cellpadding="0" cellspacing="1" border="1" style="width:800px">
                          <tr>
                            <td colspan="2">
                              <h1>VISITOR</h1>
                            </td>
                          </tr>
                          <tr>
                            <td width="150px">
                              <canvas id="canvas" width="160" height="120"></canvas>
                            </td>
                            <td>
                              <table cellpadding="0" cellspacing="10" border="0" style="width:100%">
                                <tr>
                                  <td><h1>USER</h1></td>
                                </tr>
                                <tr>
                                  <td>LastName, User</td>
                                </tr>
                                <tr>
                                  <td>Some company name here</td>
                                </tr>
                              </table>
                            </td>
                          </tr>
                          <tr>
                            <td colspan="2">
                              <img id="barcode1" />
                            </td>
                          </tr>
                          <tr>
                            <td colspan="2">
                              <h2>Expires : 01/01/2019</h2>
                            </td>
                          </tr>
                        </table>
                      </div>

`
Is there an issue with printing a canvas object?

**Comment by pithhelmet** [comment]
canvas: true

that worked.

**Comment by oculus42** [comment]
We were planning on making `canvas:true` part of the 2.0 release, but @jasonday should we kick out a 1.x version with this as a default at this point, and is there any concern about doing so?

**Comment by jasonday** [comment]
Is the option `canvas` set to `true`?

https://github.com/jasonday/printThis/blob/master/README.md#canvas

**Comment by jasonday** [comment]
I'm inclined to save it for 2.0, as the use case seems limited and is clearly a config item.
