### ISSUE TITLE
Possible to hide the page header and footer on IE

### ISSUE THREAD

**Issue by lkj7928** [jasonday/printThis#185]
Possible to remove or hide the page header (e.g. URL), and page footer (e.g. printing time) on IE?

I already know that @page{margin:0} can be used on Chrome and firefox but how about on IE??

**Comment by jasonday** [comment]
Unfortunately, I don't know of a way to do this in IE. Maybe once the chromium based engine makes it into IE, `@page` will work, but until then I don't have a solution for you.

**Comment by lkj7928** [comment]
thank you for reply : )
