### ISSUE TITLE
Print Silent no dialogs

### ISSUE THREAD

**Issue by rabihmb** [jasonday/printThis#192]
**Is your feature request related to a problem? Please describe.**
The feature isn't related to a problem, it's just an idea to improve it

**Describe the solution you'd like**
I'm currently using a Firefox add-ons called "js print" since more than 10 years; the good benefit of it that I can print in silent mode, no need show the confirmation dialog, and it remove the top header and footer information. So, can you add a feature to print automatically when press on print taking consideration to use the default printer selected.

**Comment by irvine48** [comment]
try google chrome --kiosk option to print instantly, you might get into that direction on firefox.

**Comment by jasonday** [comment]
I don't believe there is any way to effect this from within the browser. The plugin you were using was likely changing config items within Firefox to get it to print silent. We don't have those capabilities from within page javascript.
