### ISSUE TITLE
Background Graphic Remove in Print Page

### ISSUE THREAD

**Issue by arvindkumarshukla** [jasonday/printThis#195]

**Comment by jasonday** [comment]
Hi @arvindkumarshukla, printers/printer settings do not print background images by default. This is not an issue with printThis, but is the default printing behavior. Users can choose to print background images, but printThis is not able to affect this setting programmatically.

**Comment by jasonday** [comment]
https://github.com/jasonday/printThis/wiki/Styling-Printed-Content#printing-backgrounds
