### ISSUE TITLE
When debug attribute is false only first page is printed

### ISSUE THREAD

**Issue by jceduardo** [jasonday/printThis#196]
**Describe the bug**

We have an application by which printThis is used in order to print several reports, so now we are facing an issue that affect our application when user printing some reports, only first web page is printed. Debugging the problem we found "debug" attribute putting it in 'true' reports works fine (I mean all is printed) but when is 'false' the application print first page only. The exactly point of bug is line 116:

   if (!opt.debug) $iframe.css({
        position: 'absolute',
        width: '0px',
        height: '0px',
        left: '-600px',
        top: '-600px'
      });

I played with some attributes defined in this portion of code (width, height, left and top) and when the opt.debug is 'false' the application print only first page. I thought the problem could be the pixel scale, for which it was changed by percent but neither worked, including it was changed without scale neither worked.

**To Reproduce**

For security and confidentiality we cannot divulge information about application and expose it in a public form. I tried to be as explicit as possible above in such a way you can facing it.

**Expected behavior**

Now reports can be printed due we comment from line 116 to 122, but we would like to know how you solve this issue and it help to others developers that may be having same issue.

**Screenshots**

The screenshots are difficult because none error is displayed by console. The problem was found debugging code, none exception was thrown during tests. 

**Desktop (please complete the following information):**
 
- OS: MacOSX 10.14.6
- Browser: Chrome
- Library's version: printThis v1.15.1

**Smartphone (please complete the following information):**

The application is only web.

**Additional context**

The solution couldn't be put debug attribute in 'true' because in local and development it's not problem, but in QA and production is a problem, in fact this problem is happening in production environment.

**Comment by jasonday** [comment]
Hey @jceduardo, try increasing the [printDelay](https://github.com/jasonday/printThis#printdelay). Because you're printing several pages, my guess is that the iframe content needs more time to render.

**Comment by jceduardo** [comment]
ok @jasonday let me check it about your opinion.

**Comment by jceduardo** [comment]
@jasonday I already tested with your advice but it's not working yet. I increased printDelay from 4 seconds until 30 seconds (for me it's too much time) and PDF is displayed only two pages, so PDF continue with incomplete information. Do you think about it?

**Comment by jasonday** [comment]
Are you using print to pdf? Just to be sure, try an actual print.

Additionally, if your print output is multiple pages, printThis is probably not the right tool as it's for printing specific elements of a page. Not knowing your use case, it's hard to give specific recommendations, but a print specific stylesheet may be a better approach.

**Comment by jceduardo** [comment]
Ok Jason, let me explain you and I'll try to be more specific... In general I had two problems:

1. When print frame show you PDF, It has at most 3 pages in order to print (for us is incomplete information)

2. When print PDF show you PDF, It looks information without order and like objects were moved of its places (It already solved)

About Problem 1:

Imagine a web page with much information (never mind which, the important is the information), so we have printer icon when any user clicked on it and the "printThis" function is called with some parameters:

printContainer: false,
printDelay: 4000,
beforePrint: ...,
afterPrint: ...

With these parameters I got a problem, at most 3 pages can be looked into PDF, like all information were cut in any form. In this moment, I wanted debugging my code turn "debug" attribute to "true" and when clicked on printer icon again all information was looked, and when turn debug to "false" the information again was cut. None exception was thrown but I think a problem occurs here. This is the issue I reported you.

About Problem 2:

In another hand, our print functionality is a "print frame" that is displayed with several option to print including "Print To PDF", as you mention before in our case my print output are multiple pages, up to now printThis has been working well (congrats for that), It print all information about page but I had to change some parameters to:

printContainer: true,
formValues: true,
importCSS: true,
importStyle: true,
printDelay: 4000,
beforePrint: ...,
afterPrint: ...

Before the PDF appearance was displayed wrong (Into PDF information looked without order and all objects moved of its place), but with these parameters now PDF looks good. 

About Solutions: 

1. I believe here there is a bug due I turn "debug" attribute to "true" of "false" all information should be looked into PDF

2. It's OK. I think the problem here was simple: Ignorance about how to work the library printThis

**Comment by jasonday** [comment]
What `debug: true` does is leave the iframe in play, meaning the iframe is not removed after print. I think what might be happening is that because you are printing a lot of data/elements, the timing within printThis is not 'keeping up' - the iframe is being removed before all of the data is passed to the browser.

This code here is the likely culprit:
```
// remove iframe after print
if (!opt.debug) {
    setTimeout(function() {
        $iframe.remove();
    }, 1000);
}
```

You could increase the timeout substantially, which would fix your issue. We're looking into other methods, but this will likely fix your issue until we have a new version.

**Comment by jceduardo** [comment]
@jasonday this makes sense, let me implemented it and when I tested it in all environments I told you. Thank you so much for your soon response.

**Comment by jasonday** [comment]
Any status update?

**Comment by jceduardo** [comment]
Hi Jason, I'm so sorry for not response before, actually we have a lot of work. Let me some days and I'll write you about the final result. Thank you so much for ping me!
