### ISSUE TITLE
Android preview problem when changing printer or paper size

### ISSUE THREAD

**Issue by PSPTora** [jasonday/printThis#197]
**Describe the bug**
The bug only happen when I tried to print using android device.
It work perfectly fine, but when I changed the printer's destination or paper size, 
The content switch and use the whole page's content instead.

**To Reproduce**
https://jasonday.github.io/printThis/#nada
(Using Android) In the demo page, click print and change the printer or paper size.
It should show only the cat, but it's switch to something else.

**Expected behavior**
(On Android) when change printer or paper size, the content should not switch. It should stay the same like desktop pc

**Screenshots**
![Screenshot_20200109-175559](https://user-images.githubusercontent.com/40130926/72061966-73475b80-3309-11ea-96a5-6c56bd8b9b8f.jpg)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser : chrome
 - Version : 79.0.3945.117

**Smartphone (please complete the following information):**
 - Device: oneplus 3T
 - OS: Oxygen OS
 - Browser: Chrome
 - Version: 79.0.3945.93

**Comment by jasonday** [comment]
Commenting to confirm that it is an issue. I don't have an immediate fix and need to do some investigating.

**Comment by abhi21x** [comment]
Same issue happens in my case as well. Would be amazing if @jasonday could release a fix for this, as the project is really helpful already.

**Comment by zulfirman** [comment]
It also changed when I click the save pdf button on chrome, instead of kitten, it shows the same image as above.

**Comment by jasonday** [comment]
Well, that's terrible news.

I hope to look at this issue this weekend into next week. Thanks.

**Comment by matriawan** [comment]
i've same issue

**Comment by jasonday** [comment]
So, it may be due to the removal of the print iframe.

My guess is that when changing the print size, the page javascript is no longer in it's halted state and the iframe is removed.

@matriawan @PSPTora @Ph033niX @zulfirman can you either set `debug: true` or comment out line 296? https://github.com/jasonday/printThis/blob/master/printThis.js#L296

I believe that will fix the issue temporarily.

**Comment by PSPTora** [comment]
@jasonday I've tested on 3 devices and It is working as expected. 
- Windows PC Chrome
- Android Chrome 
- iOS Safari 
It seems to work fine for 10 tests now. I will test more for 7 more days to see if there any problem with this. Thank you.

**Comment by jasonday** [comment]
@PSPTora  awesome. Thanks for testing and verifying. I'm going to change the code to leave the iframe in play until printThis is initiated again, that way it prevents this timing conflict.
