### ISSUE TITLE
Blank content on high number of pages

### ISSUE THREAD

**Issue by hpez** [jasonday/printThis#200]
When the number of pages/size of html gets high the texts don't print.

**Comment by oculus42** [comment]
Please provide some details about the issue:

Does this happen on different browsers?
What kind of content are you printing?

Have you tried increasing the `printDelay`?

Can you produce an example/demo of the issue so we can better troubleshoot, or at least provide the settings you are using?

**Comment by hpez** [comment]
I've tested it with chrome and firefox and it's the same.
I'm printing a couple of pages per page on 400 pages. And yes I increased the printDelay to 5000 and no luck either.

**Comment by oculus42** [comment]
You might try using `importStyle: true` and `copyTagClasses: true` which some libraries or frameworks use.

**Comment by hpez** [comment]
tried both, no luck

**Comment by oculus42** [comment]
If you turn on `debug:true` and look at the content of the iframe, is the content there? Can you set it to Print styles and see how it looks?

Also, is this something we can see publicly, or have a demo to test?

**Comment by jasonday** [comment]
My guess is that you need to increase the printDelay to allow for the large amount of content to propagate to the print iframe.

**Comment by hpez** [comment]
It's apparently because of the data not being completely rendered.

**Comment by hpez** [comment]
I'm having the issue again. When I'm trying to print more than 20 pages or so, the pages are printed without texts, showing only borders. I tried setting `debug: true` and when I close the print dialog and check the iframe everything is loaded fine.
