### ISSUE TITLE
Page break

### ISSUE THREAD

**Issue by mali-x** [jasonday/printThis#201]
I would like to add a highcharts histogram to the report.
The page break is made in the middle of the histogram
Is there a command / function where I would like to break the sheet?
![slika](https://user-images.githubusercontent.com/5479259/75118964-161c2500-567f-11ea-9fee-c8ce65b3d620.PNG)

**Comment by jasonday** [comment]
See here:
https://github.com/jasonday/printThis/wiki/Styling-Printed-Content#page-breaks

**Comment by mali-x** [comment]
Add to .css

.page-break {
      page-break-after: always;
      page-break-inside: avoid;
      clear:both;
    }
.page-break-before {
  page-break-before: always;
  page-break-inside: avoid;
  clear:both;
}

**Comment by jasonday** [comment]
Glad that worked. Closing ticket.
