### ISSUE TITLE
Set Print Scale 

### ISSUE THREAD

**Issue by Gmtas** [jasonday/printThis#202]
Is it possible to set print options programmatically? Can I set print scale option when init printThis

**Comment by jasonday** [comment]
As far as I am aware, there is not a method to interact with the scale option programatically. 

You may be able to hack it with CSS using `transform` or `zoom`:
```
@media print {
    body {transform: scale(.7);}
}
```

**Comment by Gmtas** [comment]
its worked, thank you. I used CSS zoom :
```
$(".print-content").css("zoom", "80%");                            

$(".print-content").printThis({    
    ...
}); 
```
