### ISSUE TITLE
How do you remove the contents of the div after the printing has taken place?

### ISSUE THREAD

**Issue by cwwms2** [jasonday/printThis#203]
How do you remove the contents of the div after the printing has taken place?

The "beforePrint" function fires before the print dialog box appears. I want to remove the contents of the div after a successful print has taken place. Will I have to remove it with some sort of timer?

**Comment by jasonday** [comment]
printThis creates an iframe to clone content into for printing.

If you are creating a div and printing it using printThis, you will need to remove the div. You can write this into your own logic, or possibly use the `afterPrint` option.

**Comment by jasonday** [comment]
Do you need any further help with this issue?
