### ISSUE TITLE
Page content cutting off while printing

### ISSUE THREAD

**Issue by bsgies** [jasonday/printThis#205]
Hi,

I'm trying to print a document which is a receipt for the customer. It is a basic receipt design and line items of the receipt are placed in a table.

Which the printThis function triggers it's cutting of content of the line items (Screenshot attached below).

How do I fix this issue?

Screenshot: https://prnt.sc/s1prm0

**Comment by jasonday** [comment]
This appears to be a CSS issue and that you need to set `debug: true` to inspect the generated iframe and apply CSS styles to affect the print outcome.
