### ISSUE TITLE
caracteres especiais

### ISSUE THREAD

**Issue by alexdasilvalima2110** [jasonday/printThis#207]
ola gostaria de saber como eu posso colocar a codificação de carateres especiais!? exemplos: ç, á Não etc... no caso seria utf8. obrigado.

**Comment by jasonday** [comment]
Are the special characters not showing in the print?
Os caracteres especiais não estão aparecendo na impressão?

**Comment by alexdasilvalima2110** [comment]
Não! Os caracteres especiais n estãoaparecendo não.

Em ter, 9 de jun de 2020 17:51, Jason Day <notifications@github.com>
escreveu:

**Comment by alexdasilvalima2110** [comment]
how do i define utf8 and display the special characters? and present the line break? do i have to put it in div <br> or \ n? and that I already tried the 2 and it doesn't work !?

**Comment by jasonday** [comment]
Are the special characters inline? What does show when printThis is triggered?

More information is necessary to debug.

**Comment by jasonday** [comment]
@alexdasilvalima2110 is there more information you can provide, so that I can investigate?

**Comment by jasonday** [comment]
Any update to this issue?
