### ISSUE TITLE
Duplicate print content

### ISSUE THREAD

**Issue by kikyoluka** [jasonday/printThis#209]
**Describe the bug**
I encountered a problem, I used the plugin to print a barcode, which contains text, barcode and qarcode, when I print a lot of barcodes, the page content will be repeated from the second page,The second page repeats the content of the first page, and the third page repeats the content of the first two pages.

This is my code:
```
/* print */
Print.onclick = function () {
    $('#printmain').printThis({
        importStyle: true,
    });
};
```
**To Reproduce**
I will generate all the barcodes that need to be printed into the printmain div, and then click to call the plug-in to print

**Expected behavior**
My expected result is that the barcodes are arranged in order, like the first page of the preview page

**Screenshots**
[My Screenshot](https://i.loli.net/2020/06/11/BD9Jp7EAxHWjIrO.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: Chrome
 - Version: 84.0.4147.13 (64 bit)
 - Library's version: printThis v1.15.1

**Additional context**
I tried different printers, but they all have the same problem

**Comment by jasonday** [comment]
Because the content is "stacking" repeatedly, it sounds as if there may be a problem with the onclick event and may not be specific to printThis.

**Comment by kikyoluka** [comment]
> Because the content is "stacking" repeatedly, it sounds as if there may be a problem with the onclick event and may not be specific to printThis.

Ah thanks, I have found the problem, because the css attribute position: fixed causes the element to appear on every page of the print preview, not the problem caused by the plugin.
