### ISSUE TITLE
Bootstrap 4 grid problems

### ISSUE THREAD

**Issue by benfiratkaya** [jasonday/printThis#211]
Not working bootstrap grid system in printing view screen.

Must be:
![Screenshot_360](https://user-images.githubusercontent.com/48600092/93715573-eb417300-fb72-11ea-86b2-58bd666f8821.png)

Printer view:
![Screenshot_361](https://user-images.githubusercontent.com/48600092/93715574-eda3cd00-fb72-11ea-9ee7-a7e8b7f3b739.png)

**Comment by benfiratkaya** [comment]
I wrote custom code for @media print but I'm looking for another solution.

**Comment by jasonday** [comment]
See other bootstrap related issues:
#208

> My guess is that you're printing a specific child of Bootstrap's grid parent (`<div class="container">`), hence why the grid doesn't work correctly when only the child is copied into the iframe.
> 
> You have a few options:
> 
> * print the parent grid container and use @media print CSS to hide other elements you don't need
> * Craft new CSS to adjust the layout and import that CSS with `loadCSS`
> * use `beforePrintEvent` to write javascript to wrap the content copied into the iframe in the grid container (may not work consistently)
>
> You likely need some print specific CSS to set the same constraints or inherited ancestor classes that are present in the modal or page.

**Comment by jasonday** [comment]
Hi, any update to this issue?
