### ISSUE TITLE
Print issue - ul li span tag color is missing without base: https://jasonday.github.io/printThis/

### ISSUE THREAD

**Issue by skannanji** [jasonday/printThis#212]
Am trying to print custom chart legend, But span color is missing on print whereas i can able to see span color only when using 
base: "https://jasonday.github.io/printThis/".

```
<ul class="0-legend">
   <li><span style="background-color: rgb(0, 255, 255);"></span>apple</li>
   <li><span style="background-color: rgb(250, 128, 114);"></span>Orange</li>
</ul>
```

Screenshot:
Html UI,
![image](https://user-images.githubusercontent.com/51313846/96411990-056c8080-1207-11eb-9e8d-e48f2b4a76d9.png)
printThis output,
![image](https://user-images.githubusercontent.com/51313846/96412353-aeb37680-1207-11eb-97d0-1e30852171e8.png)

Here span color bullet is missing.

**Comment by oculus42** [comment]
Background colors do not print by default. This is not something unique to printThis. 

Please take a look at the [Wiki Page for Printing Styled Content](https://github.com/jasonday/printThis/wiki/Styling-Printed-Content) which discusses some of the limitations and ways you may be able to solve them.
