### ISSUE TITLE
Is there a way to check if the person cancelled the print job or actually printed the print job?

### ISSUE THREAD

**Issue by jeanp-fran** [jasonday/printThis#214]
Hi,
This is not necessarily an issue per se but, I am using printThis on a self check machine that I have created for my workplace and I am curious to know if there is a way of knowing whether I clicked the **Cancel** button for the print job or if I actually clicked the **Print** button for the print job?

I have the script setup at the moment so that as soon as the person clicks on **Print** it would log them out and end their session but what I did not realize was that whether they clicked **Print** or **Cancel**, it would log them out regardless.

I've given them the option to either **Email Receipt** or **Print Receipt** so I'm curious to know if there's a way to check to see if the **Print** button was actually clicked as people can make mistakes or change their minds.

They can click **Print Receipt** but then later decide to use **Email Receipt** so that they don't waste paper.

Thank you for taking a look at my question and thanks in advance for your response.

**Comment by jasonday** [comment]
I don't believe there is a way to determine whether "print" or "cancel" is clicked, as the page does not have access to the browser's internal window (print dialog).
