### ISSUE TITLE
the plugin can not find the location of images 

### ISSUE THREAD

**Issue by alideel** [jasonday/printThis#217]
in source code

 $('#basic').on("click", function () {
      $('.demo').printThis({
        base: "https://jasonday.github.io/printThis/"
      });
    });

    $('#advanced').on("click", function () {
      $('#kitty-one, #kitty-two, #kitty-three').printThis({
        importCSS: false,
        header: "<h1>Look at all of my kitties!</h1>",
        base: "https://jasonday.github.io/printThis/"
      });
    });
![asdasdad](https://user-images.githubusercontent.com/52051077/104526168-d3ef2f80-5612-11eb-872d-7176513aa0fc.PNG)

when I change the base value to true , the plugin cant find the location of images 
in my code how can I give the location of images , css , other files to plugin

**Comment by jasonday** [comment]
I assume you are trying this locally, and due to cross origin policy, I don't believe the images will load correctly.
