### ISSUE TITLE
Html appearence didn't match

### ISSUE THREAD

**Issue by bobitza** [jasonday/printThis#221]
**I have this on print on FIREFOX:** 
![image](https://user-images.githubusercontent.com/1919467/118789830-d7831380-b89d-11eb-9bcb-158825fac297.png)

**But this is html on debug:**
![image](https://user-images.githubusercontent.com/1919467/118789907-ec5fa700-b89d-11eb-9f22-3e63a5d884a5.png)
**Alot of css not applied, but css are loaded**

**In CHROME:** 
![image](https://user-images.githubusercontent.com/1919467/118792100-00a4a380-b8a0-11eb-877a-5c252b2a7f99.png)

**Comment by jasonday** [comment]
Please see: https://github.com/jasonday/printThis/wiki/Styling-Printed-Content#printing-backgrounds

**Comment by bobitza** [comment]
I set active to keepCSS from parent + selected print background and still not like normal table: 
![image](https://user-images.githubusercontent.com/1919467/118831513-84728600-b8c8-11eb-949e-fefd9c0f2669.png)

Expectation: 
![image](https://user-images.githubusercontent.com/1919467/118831582-8f2d1b00-b8c8-11eb-8298-626297a1f070.png)

**Comment by jasonday** [comment]
Yes, you will likely need to include print specific CSS to address layout differences. 

You can accomplish this in two ways:
* A print media query in the page CSS that's getting ported into the print iframe CSS
```
@media print { 
 /* All your print styles go here */
 #header, #footer, #nav { display: none !important; } 
}
```
* Or create a CSS file specifically for printing and use the `loadCSS` option
