### ISSUE TITLE
printDelay issue

### ISSUE THREAD

**Issue by mcanepa** [jasonday/printThis#222]
I was revisiting #176. I upgraded from 1.12.3 to 1.15.1 and to my surprise, the issue I reported was still happening...

As an addendum, I can say that the problem that I'm facing is that while online (not localhost), the print preview sometimes renders correctly and sometimes it doesn't (firefox and chrome)

This time around I used the `printDelay` option and changed it from 333 to 1000 and et voilà, the issue is gone. So I'm guessing that something is triggering before the plugin completely loads all the css. I've read #213 and #215 and they are similar to this.

So may be instead of a timer, the code should do what it does after some kind of `.ready()`, `.load()` or `.done()` method

Thanks!

**Comment by mcanepa** [comment]
Using Firefox's network monitor, I see that every time the print preview fails (incorrect render) it's because some styles are loaded after the preview window is shown.

If the styles are loaded fast, then the print preview shows exactly what I expected

A small printDelay, like default 333 o 500 isn't enough and make it seems like a random bug, but with larger numbers it works everytime.

So yes, as you already know...this is a timing issue

**Comment by jasonday** [comment]
That's absolutely in the plan, the issue is that the events between browsers and platforms is inconsistent, so we have to look further into it.
