### ISSUE TITLE
can't set CSS and print page size 

### ISSUE THREAD

**Issue by habeebkambrath** [jasonday/printThis#223]
am used printThis.jss and added css file from project path but print preview is not like my design alignment is different and how i can print default to A5 sheet ?

**Comment by habeebkambrath** [comment]
loadCSS: "\stylesheets\print.css",  not working ,nodejs express project with handlebars, am tried file path with different formats

**Comment by jasonday** [comment]
Answered on [Stackoverflow](https://stackoverflow.com/a/68820217/335514)
