### ISSUE TITLE
How Can i print two pages with different element for each page?

### ISSUE THREAD

**Issue by VinceSanityyy** [jasonday/printThis#225]
**Is your feature request related to a problem? Please describe.**
Just need to print two different id's in a separate paper

**Describe the solution you'd like**
I want to print 2 pages with different element per page.

**Describe alternatives you've considered**
I put two buttons to print per element which is not good.

**Additional context**
i want to print the first card as page 1 and the second one as page 2
![image](https://user-images.githubusercontent.com/38340124/134132601-4609af85-08bf-49b3-ab28-943a267ad888.png)

**Comment by oculus42** [comment]
There are some CSS options for page separation. They are not universally supported, though.

Take a look at the Wiki, we have some information on styling print content which includes [Page Breaks](https://github.com/jasonday/printThis/wiki/Styling-Printed-Content#page-breaks).

**Comment by VinceSanityyy** [comment]
@oculus42 do you have an example for it? and it is possible for my end?

**Comment by jasonday** [comment]
@VinceSanityyy no examples, as our wiki explains, there are limitations. You can read through the wiki (which we need to update a link there), but here are the relevant resources. 

* https://developer.mozilla.org/en-US/docs/Web/CSS/break-after
* https://caniuse.com/?search=break-after

**Comment by oculus42** [comment]
I don't have an example, but it is the `page-break-*` and `break-*`  CSS rules, which are supported to varying degrees for paged media. [Most of them are identified in a caniuse.com search.](https://caniuse.com/?search=page%20break)

You may find some success with a combination of them, but you will need to test on all supported browsers. You should be able to add this to your CSS or provide a print-only stylesheet that includes these rules.

Something like this might work:

```CSS
.card {
  page-break-after: always;
  break-after: page;
}
```

**Comment by jasonday** [comment]
Unfortunately not. The multiple selectors capability is the ability to select multiple elements to print, but separation is outside of printThis's capabilities and browser support is currently limited, as referenced above. You may want to try @oculus42's advice and use multiple CSS properties and test thoroughly.

**Comment by VinceSanityyy** [comment]
Okay @jasonday. Maybe the best idea for me is to put another print or a select box and choose if which page/element to print? Is that a good idea? I'm just asking about my opinion.
