### ISSUE TITLE
How can i separate or print 2 selectors on different page?

### ISSUE THREAD

**Issue by VinceSanityyy** [jasonday/printThis#226]
**Is your feature request related to a problem? Please describe.**
I just want to print 2 elements but when I do it does not look well.

**Describe the solution you'd like**
Every element is different page.

**Describe alternatives you've considered**
My alternative solution was two buttons per element but it is not good. 

**Additional context**
Here is the preview

Here is the html card with data
![image](https://user-images.githubusercontent.com/38340124/135277050-bc847133-06a7-48e9-a387-eeb502bb7b89.png)

When i want to print/download here is the preview
![image](https://user-images.githubusercontent.com/38340124/135277157-5d01d56d-bab5-4884-8d8f-226d384739ed.png)

Are there any ways to separate them? 

Here is my print code
```
           $("#pdf, #pdf2").printThis();
```

**Comment by jasonday** [comment]
https://github.com/jasonday/printThis/wiki/Styling-Printed-Content#page-breaks
