### ISSUE TITLE
Print only First Page on Firefox browser

### ISSUE THREAD

**Issue by mujtaba1016** [jasonday/printThis#227]
**Describe the bug**
When i set the property copyTagClasses: true then it shows only First Page in Preview and also prints 

**To Reproduce**
```
$('#ID').printThis({
      copyTagClasses: true
});
```

**Comment by jasonday** [comment]
@mujtaba1016 can you provide a bit more information? 

- What are you printing? 
- How many pages is it? 
- Tag classes are copied from the `html` and `body` elements, is there something in those classes interfering? 
- Have you set `debug: true` and inspected the print iframe to troubleshoot?

**Comment by jasonday** [comment]
Did you inspect the print iframe to ensure all of the expected content is within the iframe? And that there are no formatting issues?

**Comment by mujtaba1016** [comment]
Its in a bootstrap modal Popup body with overflow auto. when i set copyTagClasses to false it print all pages

**Comment by mujtaba1016** [comment]
> Is the content being printed in a floating or positioned container? As it says in the Wiki's [Basic Troubleshooting](https://github.com/jasonday/printThis/wiki/Troubleshooting-Printing-Problems) page
> 
> > Firefox has known issues cutting off content in floated containers when printing.

Its in a bootstrap modal Popup body with overflow auto. when i set copyTagClasses to false it print all pages
