### ISSUE TITLE
Specify DOM element to which the print iframe is appended

### ISSUE THREAD

**Issue by theGreatAndPowerfulOz** [jasonday/printThis#23]
First of all, thanks for this awesome plugin! It's just what I was looking for.

As I implemented the plugin on one of the pages on my site, I found that it worked perfectly right out of the box (hooray!). I then tried to employ it when clicking a button on a modal jQuery UI dialog, but found that when using IE 11 (not sure about earlier versions), the specified element was not printed. Rather, all visible content in the browser viewport was printed (sadness; sniff, sniff).

I think the issue is that since the print iframe is being appended to the "body" element, it doesn't get focus or something when ".print()" is finally executed (or something like that), since the jQuery dialog and its associated overlay div are laying on top of the main page:

```
(line 55) $frame.appendTo("body");
```

After banging my head against the wall for hours and cursing IE (not an unusual occurrence), I did a little experiment and added an "appendToEl" option (with a default of "body") to the others in your script:

```
appendToEl: "body"      // element to which the print iframe is appended
```

Then, I updated line 55 to read from the option:

```
$frame.appendTo(opt.appendToEl);
```

Finally, I updated the call in my document to specify an element that was within the jQuery UI dialog as the one to which the print iframe is appended:

```
$( "#selectorOfElementToPrint" ).printThis( {appendToEl: "#selectorOfElementInDialog"} );
```

Worked like a charm! Thought you might want to consider adding this as an option for anyone who finds the need for it, as I did.

**Comment by Nileshgraut** [comment]
Great, Working fine Thanks Guys
