### ISSUE TITLE
Sketchfab Iframe with print option

### ISSUE THREAD

**Issue by HypermedFrank3D** [jasonday/printThis#236]
I'm working on 3D configurator with Sketchfab.
It's almost done but I try to find a way to print pdf .
When I push the print button, the Iframe lose all the setting I put inside the Iframe.
The Iframe will show the intial state for print, instead the new data injected...
Sorry for my english
Here the project :
https://hypermedia-innovation.com/app/multi_3d/

**Comment by HypermedFrank3D** [comment]
![screenshot](https://user-images.githubusercontent.com/112203148/186989715-a94aea3d-0314-44cc-800d-cf4dd40ebb8f.jpg)

**Comment by jasonday** [comment]
Hi, I am not sure what you're trying to accomplish. Are you trying to inject new content when the user selects "print"? 
Looking at your code, it appears you are using native `window.print();` to print. I don't see printThis called in your code anywhere.

**Comment by HypermedFrank3D** [comment]
Sorry, you can look at now, at the same link : https://hypermedia-innovation.com/app/multi_3d/
I created a new folder for my own development...
