### ISSUE TITLE
My css not loading

### ISSUE THREAD

**Issue by ghost** [jasonday/printThis#237]
I have this page and I need to convert it to pdf
![image](https://user-images.githubusercontent.com/109739994/188251591-7931eeb5-cdfb-4230-a82c-1ff76afe87d6.png)
But I have the following return
![image](https://user-images.githubusercontent.com/109739994/188251601-2db0aa7c-8b37-49c3-9f23-2b6efd6288a9.png)
My code is this:
![image](https://user-images.githubusercontent.com/109739994/188251671-705fce29-d35a-4ffa-925e-ab4b2c7284c0.png)
Where there may be an error for not loading the css correctly? Thaks!

**Comment by jasonday** [comment]
Try using the full path to the CSS file. printThis creates an iframe and that iframe can't use relative paths, so a fully qualified URL to the CSS is needed.

**Comment by ghost** [comment]
I edited the code to the full path, but it still presents the same way as above
![image](https://user-images.githubusercontent.com/109739994/188254003-3dd5383e-67d6-47fa-ac8e-89eb8f4ceef4.png)
![image](https://user-images.githubusercontent.com/109739994/188254074-77783edf-2c2f-4bd9-b32c-414f21ec488c.png)

I need to add some more properties?

**Comment by jasonday** [comment]
To reference files on your hard drive, you may need to do the following:

```
file:///C:/mystyles.css
```
But if you're using `localhost` then it would be something like:

```
http://localhost:8080/mystyles.css
```

**Comment by ghost** [comment]
The command prompt calls css.
But in the pdf it is still different from the website
![image](https://user-images.githubusercontent.com/109739994/188272233-74756384-cff0-4a75-895f-498508b7c2c8.png)
![image](https://user-images.githubusercontent.com/109739994/188272283-0d3eb082-da40-48bc-8375-767537aa3a7b.png)
![image](https://user-images.githubusercontent.com/109739994/188272310-18b8a0ac-7ed2-4c11-96d2-4c4130f923b6.png)
![image](https://user-images.githubusercontent.com/109739994/188272335-eb6f799f-8b1d-44c4-a633-c381f21c4ea7.png)

**Comment by ghost** [comment]
In this configuration I still get the same output

![image](https://user-images.githubusercontent.com/109739994/188272754-b4e2aff3-6b12-4276-8475-65500bb22b12.png)
![image](https://user-images.githubusercontent.com/109739994/188272771-599b8d77-1812-4fd9-aa0d-9d00939823b0.png)

**Comment by ghost** [comment]
Hello I solved loading the style inside the html div.
Thank you for your help!
