### ISSUE TITLE
Direct download PDF without popup preview.

### ISSUE THREAD

**Issue by webstar027** [jasonday/printThis#238]
Hello, Thanks for your sharing this script.
I am going to use this for my application.
BTW, is there anyway to download pdf with A4 format without opening preview popup?
Thanks

**Comment by jasonday** [comment]
Hi @webstar027 it's not possible to bypass the print system dialog. Print is a system function, and all we can do is initiate it, but settings like PDF or paper size are not configurable in a programmatic way.
