### ISSUE TITLE
debug: true not working

### ISSUE THREAD

**Issue by tahiriqbalnajam** [jasonday/printThis#239]
**Describe the bug**
Hi, 
I am trying to debug, and for this, I have set debug: true but the plugin is rendering print, not iFrame.
 $('body').printThis({
        debug: true,               // show the iframe for debugging
        importCSS: true,            // import parent page css
        importStyle: true,          // import style tags
        printContainer: true,  
})

**Expected behavior**
Should open an iFrame.

**Desktop (please complete the following information):**
 - OS: Window
 - Browser Chrome105.0, Firefox105

**Comment by jasonday** [comment]
`debug: true` doesn't open an iframe, it creates an iframe before the closing `</body>` tag (about 200x200 pixels in size). Did you scroll down to the bottom of the page to verify that the iframe was not being created?

**Comment by tahiriqbalnajam** [comment]
Thank you I got it,
As the page was a little long so was not able to see this iframe,
