### ISSUE TITLE
Printable Area

### ISSUE THREAD

**Issue by craigbass76** [jasonday/printThis#247]
I'm not sure how to define page margins reliably, mostly top and bottom where content runs across a page break. When I'm using pandoc/weasyprint to make HTML and PDFs, I've specified a `<div class="pb">`, and styled it `{ page-break-before: always; }`, but Weasyprint took care of actual paper margins for me. I'm not sure how to do the same thing with printThis, or even if I can. 

![pageBreak](https://github.com/jasonday/printThis/assets/12818479/0ed4ee94-ec14-4d94-a77d-9cdd4cd02f9a)

Are there some good working examples out in the wild to look at?

**Comment by jasonday** [comment]
There's not a lot of reliability, but you can try to use the `@page` directive.

i.e. - 
```
 @page {
        size: A4;
        margin: 0 !important;
    }
```
