### ISSUE TITLE
Loading a Style Sheet

### ISSUE THREAD

**Issue by craigbass76** [jasonday/printThis#251]
I can't seem to figure out how to get a specific style sheet loaded for PDF printing. I've tried `http://mysite.com/stylesheet.css`, `/stylesheet.css`, `./stylesheet.css`, and (because I'm using Apache's mod_rewrite, and what's getting printed is "technically," four directories deep, even though it's all just `viewdoc.php`) `../../../../stylesheet.css`.

But I can't seem to call the PDF stylesheet. PrintThis is always snagging the regular stylesheet.

Here's my testing site's copy of `printThis.js`: https://lbmliftoff.com/documentation2/printThis.js

A sample doc: https://lbmliftoff.com/documentation2/docs/module/personalAndAdmin/getting_support

Right now I've got a blue H1 on the regular stylesheet (#0000ff) and a red one in the PDF stylesheet (#ff0000) so I can see at a glance whether I'm calling the right stylesheet when I create PDF.

What'd I do wrong?

**Comment by jasonday** [comment]
A couple of things:
* printThis will copy over the parent page's CSS and styles by default, unless you tell it not to:
```
  importCSS: true,                    // import parent page css
  importStyle: true,                  // import style tags
```
* When debugging, set `debug: true` which will allow you to inspect the iframe printThis creates to verify that the print content is correct and that defined stylesheets are being loaded in that iframe.

**Comment by jasonday** [comment]
Performing a quick test, and your specified CSS is loading and the H1 is red.

**Comment by craigbass76** [comment]
@jasonday Right. If the H1 is red, I know it's loading my PDF stylesheet instead of the web one (which is blue)

**Comment by craigbass76** [comment]
I'm lost... https://lbmliftoff.com/printTest/webPage.html  I copied things over to have a place to play, and now it's not loading ANY css. I've tried commenting/uncommenting/editing a few lines in printThis.js, and dorked with things in the html (starting down about line 170).
I feel like the issue is staring me in the face...

**Comment by jasonday** [comment]
> @jasonday Right. If the H1 is red, I know it's loading my PDF stylesheet instead of the web one (which is blue)

Reread my comment. The print view was showing a red H1, meaning your print-specific PDF CSS was loading correctly in the printThis iframe. 

![Capture](https://github.com/jasonday/printThis/assets/748011/89ca0291-15a6-4a68-b49f-c54c1b49873a)

**Comment by craigbass76** [comment]
Bah, I see it now too, but wasn't last night. I was doing hard refreshes (Ctrl Shift R) but was something perhaps getting cached?
Seeing it today too - I'm changing the left margin on the H1, and it doesn't move on the next print operation

**Comment by jasonday** [comment]
Yeah, you're getting cached somewhere because printThis is creating iframes dynamically, it's not the cause. You need to turn off caching, if able. You can also try using incognito mode during development to see if that helps.
