### ISSUE TITLE
doesn't work correctly in RTL websites

### ISSUE THREAD

**Issue by aliajboy** [jasonday/printThis#255]
**Describe the bug**
if you have an rtl website and use this, All the texts go to the left and disorganize.  
and the texts and fonts are different from what the page is showing. It would be great if you could fix this. 

Original : 

![original](https://github.com/jasonday/printThis/assets/73298440/b7671be6-84a8-4077-bbfd-059d02d56c67)

Print Preview:

![after](https://github.com/jasonday/printThis/assets/73298440/32ee700d-1604-4fac-978e-8b4735c636ce)

**Comment by jasonday** [comment]
Try adding `dir="rtl"` to the selector you are specifying for print.

**Comment by aliajboy** [comment]
I used `dir="rtl"` as you can see. the page shows everything OK! but after the print preview opens, everything goes ltr
