### ISSUE TITLE
Chrome ignores pageTitle option

### ISSUE THREAD

**Issue by helgatheviking** [jasonday/printThis#27]
The `<title>` tag is being set in the iframe, but nevertheless, the Print headers still show the title of the parent page.

**Comment by mcanepa** [comment]
This is happening to me too.

printThis 2.0 and chrome 131.0.6778.85

@helgatheviking did you solve this?

**Comment by helgatheviking** [comment]
No, I don't even remember trying to use this. L.. it's been 10 years. 😅

**Comment by mcanepa** [comment]
@jasonday any ideas? please help

**Comment by mcanepa** [comment]
It's a chrome issue

I filled a bug report: https://issues.chromium.org/issues/382394786
