### ISSUE TITLE
Error when print in modal jQuery UI dialog

### ISSUE THREAD

**Issue by BG-PR** [jasonday/printThis#37]
Hello.
I'm using last verion of jQuery and jQuery UI (both 1.11.1).
When I tried to use printThis, when modal jQuery UI dialog is on screen - it print the entire page's content, not only selected.
Link to fiddle: http://jsfiddle.net/4kf6gqqb/4/

Note that the problem is only in Internet Explorer. It's work in FIrefox.

**Comment by oculus42** [comment]
No follow-up for years. Closing.
