### ISSUE TITLE
Chart width clipped in Chrome

### ISSUE THREAD

**Issue by Jerther** [jasonday/printThis#40]
Hi! Really like your library!

I found this problem with Chrome and DevExtreme charts.

http://jsfiddle.net/nphwtrrL/

Resize the result window to the maximum and hit the print button. Notice the chart is clipped to the right. Try the same thing in Firefox and the chart is correctly sized.

**Comment by Jerther** [comment]
Anything yet?

I was thinking of calling some function that would re-render the chart after the content has been transfered to the iframe. dxChart has a render() function. Could that work?

**Comment by jasonday** [comment]
Sorry, the holidays got the best of me.

You could try and rerender the chart, but then you'd probably have to alter
the plugin to do that.

**Comment by djdance** [comment]
+1, this is Google charts, I think it has moved to the next page by Windows, not by your library, but please maybe we could set some force page break code where we want?

the black line at the top of the screenshot is Window's Chrome print dialog between pages space.

![cropimage](https://cloud.githubusercontent.com/assets/2269720/22626309/b58fb746-ebbb-11e6-8f8b-50301e838647.png)

**Comment by jasonday** [comment]
@djdance I don't think the plugin should manage page breaks. This can be managed much easier in the CSS for your page. See this [stackoverflow.com answer](http://stackoverflow.com/a/1664058/335514) which specifies how you can control where the page breaks when printing.

**Comment by oculus42** [comment]
Agreed. You can add page break styling to the page directly or using the [loadCSS](https://github.com/jasonday/printThis#loadcss) function.

**Comment by jasonday** [comment]
@Jerther have you tried the latest version?

**Comment by Jerther** [comment]
@jasonday I'm sorry, I'm no longer on the project which used printThis. I no longer work there... I'm not even sure the project has been continued. :/

**Comment by jasonday** [comment]
@Jerther - thanks. I'm going to close as we've added canvas support (experimental) since this ticket was opened.
