### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by eraniichan** [jasonday/printThis#44]
So I'm trying to use this for my asp page.
I included these at the head section:

    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script type="text/javascript" src="https://dl.dropboxusercontent.com/u/36032609/printThis.js"></script>

and this is the division that I want to be printed:

    <div id="viewentry" class="modal hide fade " tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
        <div id="viewMdlBody" class="modal-body" style="min-height:400px;">
        </div>
        <div class="modal-footer">
            <button id="btn" >Print</button>
			<button id="createlessBackBtn" class="btn" data-dismiss="modal" aria-hidden="true">Back</button>
		</div>
    </div>

And lastly, I fired the event using this: 
$(document).ready(function () {
            $('#btn').click(function () {
                $('#viewentry').printThis();
            });
        });

But in the end when I go to the console, it says something like this: 

Uncaught TypeError: undefined is not a functionStoreVisitView.aspx:57 (anonymous function)jquery-latest.min.js:3 m.event.dispatchjquery-latest.min.js:3 m.event.add.r.handle

**Comment by jasonday** [comment]
You may have issues due to cross domain policy. Your assets are mixed http/https, and this could be your problem

**Comment by eraniichan** [comment]
I tried saving the js into a js file but still no luck with it.

**Comment by jasonday** [comment]
If you look at the readme,  it states that if you want help debugging I
will need to see a live page, or a jsfiddle/jsbin. I am unable to
troubleshoot the code if you simply state "it's not working.

Thanks for understanding.

**Comment by eraniichan** [comment]
Ok so I managed the plugin to make it work.
But can I ask how I can print the whole modal window? Because when I set try to print it, it has scrollbars in it.

![print1er](https://cloud.githubusercontent.com/assets/11989520/7222987/1a3ebf78-e74c-11e4-827e-d9820bd30ff9.PNG)

and here's my code for the printing:

$("#div2").printThis({
                    debug: false,
                    importCSS: true,
                    importStyle: true,
                    printContainer: true,
                    loadCSS: "css/bootstrap.css",
                    pageTitle: "print",
                    removeInline: false,
                    printDelay: 333,
                    header: null,
                    formValues: true
                });

and I noticed that the style was not loaded properly for printing, because this was the look of my modal window.

![scre1](https://cloud.githubusercontent.com/assets/11989520/7223001/8ceae510-e74c-11e4-897f-c7a5d14d1ea8.PNG)

**Comment by jasonday** [comment]
Set debug to true, and then inspect the iframe to determine if the CSS is being injected into the iframe. You may need to use the full path for the CSS.

**Comment by oculus42** [comment]
You will probably add print styles to remove/override the explicit height of the element.

**Comment by jasonday** [comment]
No further response. Closing.

**Comment by jamsshhayd** [comment]
How was your issue resolved ?

**Comment by kapilSoni101** [comment]
@koreguy -sir i got $(...).printThis is not a function can you tell me how to fix above error?

**Comment by MihalIvanych** [comment]
> @koreguy -sir i got $(...).printThis is not a function can you tell me how to fix above error?

I have the same problem, did you solve it?

**Comment by JasonXaristides** [comment]
I solved it by using the following CDN imports at the bottom of the page.

```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/printThis/1.15.0/printThis.min.js" integrity="sha512-d5Jr3NflEZmFDdFHZtxeJtBzk0eB+kkRXWFQqEc1EKmolXjHm2IKCA7kTvXBNjIYzjXfD5XzIjaaErpkZHCkBg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```
