### ISSUE TITLE
Prints Blank Page in iOS 8

### ISSUE THREAD

**Issue by jeffda** [jasonday/printThis#46]
This plug-in only prints a blank page and footer information when printing from Safari in iOS 8.

https://jsfiddle.net/u1pvspqo/

**Comment by jasonday** [comment]
Due to cross-domain policy, resources is jsfiddles have to be loaded over https, so the fiddle is not working. Please correct and I can assist with debugging.

Additionally, have you set debug: true to inspect the plugin created iframe to determine if the contents are being written in?

**Comment by jeffda** [comment]
https://jsfiddle.net/u1pvspqo/4/

The iframe gets loaded just fine, and it prints fine in iOS 7. It's just iOS 8 that prints a blank page.


--
Sincerely,

Daniel Jeffery
Web Development Specialist
www.jefkostudio.com
www.linkedin.com/in/djefko

**Comment by jeffda** [comment]
Looks like it does work in jsfiddle, just needed to accept the certificate. Still not working in another application, so I'll review that other app's code.


--
Sincerely,

Daniel Jeffery
Web Development Specialist
www.jefkostudio.com
www.linkedin.com/in/djefko

**Comment by jeffda** [comment]
Weird, now everything is working.

**Comment by jasonday** [comment]
Glad everything is working for you.

Thanks for using the plugin!
