### ISSUE TITLE
IE9 Style Problems

### ISSUE THREAD

**Issue by tswardenski** [jasonday/printThis#47]
Awesome plugin. It's working great for every browser and version I need aside from IE9. I've spent time in debug mode and the iframe is styled correctly with all the styles I've imported, however when the page is actually printed none of the styles are being respected. I'm sure there are IE9 specific bugs when it comes to print styles, but even a basic `text-align: center;` isn't being respected on my section headings.

Have you seen these issues before or know why this would be the case for that browser?

Thanks!

**Comment by jasonday** [comment]
Do you have access to a page I can debug? You can send me a note at jason
[at] rathernerdy.com if the site is not for public consumption.

**Comment by tswardenski** [comment]
Sent you an email. Thank you!
