### ISSUE TITLE
Value should be quoted.

### ISSUE THREAD

**Issue by ramin32** [jasonday/printThis#57]
line 156 should have the quotes by the value as well, otherwise it crashes for complicated values:
`$doc.find('input[name="' + $name + '"][value="' + $value + '"]').attr('checked', 'checked');`

**Comment by jasonday** [comment]
Please explain 'crashes' and 'complicated values'. Thanks.

**Comment by ramin32** [comment]
Complicated values: values with a space or perhaps non-alphanumeric characters.
Crashes: JS throws a jquery error and js execution stops.

You have the quotes in the name attribute, might as well have it for the value as well...
