### ISSUE TITLE
how can I hide the div layer?

### ISSUE THREAD

**Issue by bluestonemds** [jasonday/printThis#58]
Thanks for you making the great plug-in.This plug-in works fine for me. there is  a problem about jQuery function Show() and Hide.

Here the thing is that I want to print a receipt.I just don't want to show the div layer of the receipt to user.so I hide the layer when the page loaded .

the script is here.
 ```$(document).ready(
        function () {
            $("input#printBtn").click(function () {
                $("#myPrintArea").show();
                $("#ifPrint").val('1');
                $("div#myPrintArea").printThis({
                    debug: false,
                    pageTitle: ""
                });
               $("#myPrintArea").hide();
            });
        });```
but I run the script and the print page was blank.is it hidden directly?
Any help will be appreciated.

**Comment by jasonday** [comment]
My guess is that there is some issue with the show, depending on how you have the code set. jQuery .show() adds an inline style 'display: block' and it may not be getting picked up by the plugin. Without digging into this further, a quick fix is to add this to your css:

    @media print {
        #myPrintArea {
            display: block;
       }
    }
