### ISSUE TITLE
Table not printed in full

### ISSUE THREAD

**Issue by marko89kv** [jasonday/printThis#60]
Hello,

when I try to print a long HTML table, it isn't printed in full, it just gives the first page, and then it gets cut off.

**Comment by jasonday** [comment]
>Please read:

>I ask all users reporting bugs to:
>    - create a jsfiddle (http://www.jsfiddle.net) or give an example url
>    - set the option "debug: true" and inspect the iframe created by printThis and report on what is contained in the iframe

>I am unable to debug with limited information and need each user to actively participate in the debugging process.

**Comment by jasonday** [comment]
No further response. Closing.
