### ISSUE TITLE
Shouldn't base take context path into concideration also, links broken.

### ISSUE THREAD

**Issue by trashhead** [jasonday/printThis#61]
My Web app path: localhost:8080/turbo.
When I print I get: 
<base href="http://localhost:8080">
<link type="text/css" rel="stylesheet" href="vendor/font-awesome/css/font-awesome.min.css" media="all">

Error cannot find : http://localhost:8080/vendor/font-awesome/css/font-awesome.min.css 

Its missing turbo path .

**Comment by trashhead** [comment]
Maybe a solution like this ?
$head.append('<base href="' + document.location.protocol + '//' + document.location.host + document.location.pathname+'">');

**Comment by Cdenby** [comment]
Any suggestions on workarounds for this?

**Comment by trashhead** [comment]
I'm new to github, I made a branch here https://github.com/trashhead/printThis/blob/patch-1/printThis.js
It adds a new parameter called baseURL where you can add your own base-url.

**Comment by Cdenby** [comment]
I don't think that worked. Unless I'm getting the syntax on it wrong:
$("#pnlTheReport").printThis({baseURL:"http://localhost/app"});
I don't think this will do it in the long term. I can't tell what my clients will be doing with the app name eventually and it's a bit of a pain to adjust inside the javascript.

**Comment by trashhead** [comment]
What if you have a dynamic path, something like this:
location.protocol+"//"+location.hostname+location.pathname

**Comment by JohnMaina** [comment]
Did you find a permanent solution for this?

**Comment by jasonday** [comment]
Test again.
