### ISSUE TITLE
Cannot see the text of select elements on print screen

### ISSUE THREAD

**Issue by Venkatramani** [jasonday/printThis#64]
Hi,

I'm using v 1.5 of your plugin.

I cannot see the selected text of select element, when i print.

http://jsfiddle.net/dJjMz/109/

Please help me in debugging this.

**Comment by jasonday** [comment]
The javascript you are using is not the printThis plugin:
http://healyconsultants.com/hcwp/wp-content/themes/healy/js/printThis.js

I would reach out to that author for assistance.

**Comment by Venkatramani** [comment]
Hi Jason,
Yes, After I submitted this ticket, i worked on another plugin, but same result.
So just fixed it by hiding the select elements on print.

Thanks for your response.

**Comment by jasonday** [comment]
I'm happy to help and debug printThis; let me know.

**Comment by caseyjhol** [comment]
This demo illustrates that the issue still exists with the actual printThis plugin: http://jsfiddle.net/caseyjhol/0uepdgLa/
