### ISSUE TITLE
Images not loading 

### ISSUE THREAD

**Issue by luccotta** [jasonday/printThis#67]
Hello, 

I'm using Chrome. 
Please check this example I did:

http://lucascotta.comlu.com/newspaper.html

Do you see the big text-image at the beginning of the right column? This comes from an external source and may take some time to load. 

At the top, I included the print button with the following JS:
```
$("#finalPrint").printThis({
	importCSS: true
});
```

If you try it, you can see that the image is not loaded in the print window.
If I include a `printDelay: 500` then the image loads fine. 
But the problem is that in my real app, there are about 50 images, and I have to put a big delay such as 6000 so all images are loaded...

Am I doing something wrong? Would you suggest me to do something?

Thanks!!!

**Comment by jasonday** [comment]
Unfortunately, printThis is unlikely to work for the scenario you describe.
printThis is designed for printing portions or snippets of a page. Your use
case is well outside of the parameters of normal functionality.

If you're printing an entire page, I would suggest using the print media
query in place of printThis.

Good luck.

**Comment by luccotta** [comment]
Got it, thanks!
