### ISSUE TITLE
When will a version with the printDelay option be released?

### ISSUE THREAD

**Issue by micronaut** [jasonday/printThis#69]
We are including the plugin by bower so we are getting version 0.1.2.  The content we are printing is not finished loading in the iframe that printThis creates, but using the latest code with the printDelay option appears to fix this, so I was wondering when there will be a released version with this option.  Thanks!

**Comment by jasonday** [comment]
Good catch. I may be looking at some alternative methods to printDelay this weekend (potentially removing the need for it). After I settle on whether it stays or goes, I'll update bower.

**Comment by micronaut** [comment]
Thanks for the update and quick reply!
