### ISSUE TITLE
Don't show background color?

### ISSUE THREAD

**Issue by thearabbit** [jasonday/printThis#70]
First thanks for your package.
It don't show `background-color:r ed` (but show in normal page)
```js
<div style="background-color: red">
.................
</div>

// JS
'click #print-report'(event, instance){
        let opts = {
            importCSS: true
            importStyle: true
        };
        $('#print-data').printThis(opts)
        ;
    }
```

**Comment by thearabbit** [comment]
I use `Meteor JS`, and then I tried to add `css file`
```js
// Structure
```js
/mypro
   /simple-post
      /imports/
         /ui
             /stylesheets
                 report.css
```
  
'click #print-report'(event, instance){
        let opts = {
            loadCSS: "/simple-pos/imports/ui/stylesheets/report.css"
        };
        $('#print-data').printThis(opts);
    }
```

**Comment by jasonday** [comment]
Background colors and images don't print by default.

It is a printer option your users could change, but you absolutely can't count on your users knowing or doing that. The alternative is to designate specific colors in the print CSS, removing background colors and changing font colors.

**Comment by anwar7736** [comment]
afs
