### ISSUE TITLE
Custom style does not loaded

### ISSUE THREAD

**Issue by khudadad12** [jasonday/printThis#72]
When I load my css file in loadCSS it does not load and my print section getting mess up. 
this is my the line of code: 
`loadCSS: ["assets/css/vendor/bootstrap.min.css","assets/css/main.css"],`
how do I solve it?

**Comment by jasonday** [comment]
Try it with a full path.

**Comment by Snippo** [comment]
I ran into the same problem. The problem is that the base url is not correct.
Changing line 95 in printThis.js with the following solves it for me:
```javascript
var loc = window.location.pathname;
var dir = loc.substring(0, loc.lastIndexOf('/'));
$head.append('<base href="' + document.location.protocol + '//' + document.location.host + dir + '/">');
```
Maybe not the prettiest solution but it should work.

**Comment by jasonday** [comment]
@Snippo - create a pull request with the change, test it, and I'll get the change in.

**Comment by bhorsey** [comment]
@Snippo I tried your changes to line 95 and I still can't pull in a custom style sheet. Not sure what is going on, tried setting importCSS: true, and loadCSS: with the custom path neither is pulling styles.

**Comment by Geezerdiamond** [comment]
I've submitted a pull request for a change I made which adds a new parameter to inherit the BASE tag exactly from the parent.
