### ISSUE TITLE
A problem occurred with this web page so it was reloaded (ios)

### ISSUE THREAD

**Issue by ModestGenius** [jasonday/printThis#73]
This is by far my favorite plugin for printing specified areas. Kudos to you in every respect.

Someone brought to my attention an issue that's happening on mobile safari. 

Everything is fine until after the print or cancel, where the dreaded message:

> A problem occurred with this web page so it was reloaded

raises its ugly head. 

Any able to confirm this by chance?

**Comment by jasonday** [comment]
herm....interesting & ugly. 
I'll have to do some testing at work to verify. If anyone else runs into this, please post your findings.

**Comment by ModestGenius** [comment]
@jasonday Thank you Jason. I'm digging now. Will let you know if I find any gold.

**Comment by ModestGenius** [comment]
@jasonday Well that was interesting. Seems iOS (safari) just wanted a little more time to process the contents of the print window before the removing it from the DOM. 

```
//remove iframe after print
if (!opt.debug) {
    setTimeout(function() {
        $iframe.remove();	                    
    }, 2500); // prev value was 1000
}
```

**Comment by jasonday** [comment]
Good catch. This is why I don't like using setTimeouts, but currently stuck with them.

**Comment by ModestGenius** [comment]
@jasonday what was the resolution for this? Did you find another way other than increasing the timeout like my example?
