### ISSUE TITLE
Layout messed up with two tables

### ISSUE THREAD

**Issue by startovernow** [jasonday/printThis#76]
I need to print a jquery dialog contains two tables on the top of each other. On screen it shows perfect layout, but  print out page the bottom table's (Total) column's width is messed up, as shown below.

Any help is greatly appreciated!
![displayed](https://cloud.githubusercontent.com/assets/18681747/20009049/f770487c-a270-11e6-89bc-1f8b5c782bb7.png)
![printed](https://cloud.githubusercontent.com/assets/18681747/20009064/05503f56-a271-11e6-969a-3efa42aeb578.png)

**Comment by oculus42** [comment]
You can see a pixel of difference in the alignment one the first image.

Try enabling `debug` and inspecting the CSS differences.  

Are the two tables using different methods for calculating size, like pixels and percent?  
Are the styles setting the width of one of the tables depending on a parent element/class that doesn't exist for the printThis version?

**Comment by startovernow** [comment]
@oculus42, Thank you! You are correct. two tables with two css. I loaded with new css when printing and it works fine. I am closing this issue.
