### ISSUE TITLE
Bootstrap gradients not carrying over?

### ISSUE THREAD

**Issue by SpringsTea** [jasonday/printThis#79]
I'm trying to print a container containing standard bootstrap panels, that are colored with things like           `.panel-success`.

The panels show up, but the header color is missing, so the only color that shows are the borders. Does printThis not work with gradient baackgrounds?

Heres a pictures of what it looks like for me: http://i.imgur.com/YeXKn6Y.png

**Comment by oculus42** [comment]
By default backgrounds are not printed. You can enable this during the print process, but I think Bootstrap intentionally removes their backgrounds in a print media query. Try just printing your content regularly and see if the backgrounds appear as expected.

**Comment by SpringsTea** [comment]
Ah, I see what you mean. Thats super lame. So I would have to edit boostraps print media rule out of the minified file. What a pain. Thanks
