### ISSUE TITLE
Missing tag 1.5 results to bower fetching outdated package

### ISSUE THREAD

**Issue by mizzos** [jasonday/printThis#80]
According to the file printThis.js the recent version of printThis ist v1.5.
The file printThis.jquery.json refers to v0.1.4.
However bower only recognizes v0.1.1 and v.0.1.2 and therefore it is not able to download the most recent version. No matter what, I can not get bower to download any other than v0.1.1 or v.0.1.2

This is very confusing. After all, I do not want to add printThis manually to my project.
Could you please make shure the tags/versions match the development of this pretty cool plugin?

**Comment by jasonday** [comment]
please try again.

**Comment by mizzos** [comment]
Thank you for taking care of this issue!
