### ISSUE TITLE
Problem with Printing Additional Resources (Images)

### ISSUE THREAD

**Issue by tetrahydra** [jasonday/printThis#89]
Hello,

I am having a problem when printing content with images. The document does not have "BASE"

Original page is:

http://192.168.1.20/mypass/special_cases_7_United_Kingdom_Identity_Cards_Passports

but when printed

Failed to load resource: the server responded with a status of 404 (Not Found)
http://192.168.1.20/assets/images/ukpass/idcardschemesss_3521954b.jpg 

This is because it skipped the folder /mypass/
The correct path was
http://192.168.1.20/mypass/assets/images/ukpass/idcardschemesss_3521954b.jpg 

In the HTML, code for image was
assets/images/ukpass/idcardschemesss_3521954b.jpg 

How can I solve this.

**Comment by oculus42** [comment]
You should be able to set a base URL to indicate the relative path for content like the image. Something like this: 

    $(selector).printThis({base: '/mypass/'});

**Comment by tetrahydra** [comment]
Thanks... It works like a charm.

But when testing on the real server and with Google Adsense, it pops up this error

> pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:17 Uncaught TagError: adsbygoogle.push() error: All ins elements in the DOM with class=adsbygoogle already have ads in them.

But when use Adsblocker, the problem's gone.

**Comment by oculus42** [comment]
My first suggestion would be to not print a container that has ads in it, if possible.

Barring that, this is a bit of a workaround and consumes more resources, but you could do something like this:

```javascript
$(selector)
  .clone()             // Make a copy
  .find(adSelector)    // Locate the Ads
  .remove()            // Remove them from your copy
  .end()               // Back up to the DOM clone
  .printThis(options); // Run printThis on it

**Comment by oculus42** [comment]
No follow-up in two weeks. @tetrahydra

**Comment by tetrahydra** [comment]
I am not able to test at the moment (away for research), will update next week.

**Comment by tetrahydra** [comment]
Managed to connect to the network and the method works! Superb. Thank you.

**Comment by jasonday** [comment]
Great! thanks.
