### ISSUE TITLE
Problem with popping up the print page if previously i pressed the esc key

### ISSUE THREAD

**Issue by mykhie** [jasonday/printThis#94]
Hey guys,
When i click my print button for the first time the print window pops up nicely with my contents.
when i press esc to exit the print window and try to print again nothing happens,
the print pop window does not appear till i reload again

**Comment by jasonday** [comment]
Hi @mykhie , 
as you may have seen when you opened an issue, there was a framework for authoring a ticket. Without those details it becomes incredibly difficult to troubleshoot your issue. As stated in the readme:

> - "It's not working" without any details is not a valid issue and will be closed
> - A url, or html file, is necessary to debug. Due to the complexities of printing and this plugin, an example is the best way to debug
> - When troubleshooting, set debug: true and inspect the iframe. Please report your findings when reporting an issue
> - Every user should be active in the debugging process

I just performed a quick test in Chrome, and I was unable to recreate your issue. Please provide more details as requested.

**Comment by oculus42** [comment]
Sounds like the issue is more likely with the calling event handler, but example code would really help troubleshoot.

**Comment by oculus42** [comment]
@mykhie Any follow-up?

**Comment by mykhie** [comment]
hey guys,sorry i did get back.I realized it was the was i calling it using angular,so i had to change the all logic

**Comment by oculus42** [comment]
Sounds good.
