### ISSUE TITLE
Remove Anchor from Content

### ISSUE THREAD

**Issue by tetrahydra** [jasonday/printThis#95]
How can I remove the anchor from showing double content.

<a href="MP-76" data-pjax data-target="#main_content" class="preview_master_photo" title="<img src=image/lp/MP.jpg class=img-responsive>">MP-76</a>

When I print this, it shows as

MP-76 (MP-76)

**Comment by jasonday** [comment]
Hi,
The format for opening issues is there because there are a lot of variables that are involved in printing.

That said, my guess is that you are using bootstrap or another framework that has something along the lines of:

```
@media print {
  ...
  a[href]:after {
    content: " (" attr(href) ")";
  }
  ...
}
```

changing it to `content: ""` will fix the issue.
