### ISSUE TITLE
printout Zooming out occasionally 

### ISSUE THREAD

**Issue by adgfx** [jasonday/printThis#98]
> short description of the bug / issue, provide more detail below.
I am using this on our internal CRM System for quite long. All except one section have this peculiar problem of "zooming out". The printout is too small to read or the output is printed on the corner of an A4. It doesn't happen on a regular basis. What might be the issue? We have a "BS span 6" on the left displaying all the invoices and clicking an icon displays the actual printable invoice on the right side panel. Designated users can click "Print" from the right panel to get a copy. The print container contents are loaded by a different php file when somebody clicks "view" button against each invoice. As the data is too sensitive i can't post any details here.
====================================================================

###### `[  paste a link to an example (demo or active link) of the issue here ]`  

Your issue may be closed without active code to debug. Options include jsfiddle, jsbin, codepen, dropbox, etc. with code highlighting the specific issue you are having

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is the observed behaviour?

...  

====================================================================

#### When you set `debug:true` and inspect the iframe, what do you see?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which printThis version are you using?
- Did this work before?

**Comment by oculus42** [comment]
That is not much information to go on.

As the template suggests:
When you set `debug:true` and inspect the iframe, what do you see?

Is the content of the iframe also "zoomed out"?

Have you tried different browsers?

Are you using the latest version of the plugin?

**Comment by oculus42** [comment]
@adgfx Any follow-up?

**Comment by adgfx** [comment]
Yes, I had the container (and most of the inner elements) set to 100%, I set a max-width @media print css to fit the A4 width and it fixed the issue for time being.
