### ISSUE TITLE
Elements get deleted on page after printing

### ISSUE THREAD

**Issue by madeinffm** [jasonday/printThis#99]
> When selecting elements for printing in the footer, the elements are being deleted from the DOM.

====================================================================

I can't post a link unfortunately, but here's my printThis call:

onclick="$(this).closest('.nst-is-expanded').printThis({base:true, printDelay:600, footer: $('.legend'), importCSS: false, loadCSS: 'stylesheets/print.css'});"

====================================================================

#### What is the expected behaviour?

The element with the class "legend" should not be deleted from the DOM when printing.

====================================================================

#### What is the observed behaviour?

When the link is triggered, the element "legend" is deleted from the DOM.

Any ideas how to stop printThis from deleting the element?

thanks!

**Comment by madeinffm** [comment]
Fixed it, solution:

`footer: $('.legend').clone()`

**Comment by oculus42** [comment]
We should correct the behavior of header and footer jQuery objects to clone for you.
